Ext.define('erp.materialInventory.model.MaterialInventoryManager', {
	extend: 'Ext.data.Model', 
	fields: [
		{ name: 'hxbj', type: 'int' },
		{ name: 'ckmc' },
		{ name: 'kzdj', type: 'float'},
		{ name: 'sdbj', type: 'int' },
		{ name: 'wxbj', type: 'int' },
		{ name: 'wgbj', type: 'int' },
		{ name: 'glrk', type: 'int' },
		{ name: 'gltk', type: 'int' },
		{ name: 'zsbj', type: 'int' },
		{ name: 'gjbj', type: 'int' },
		{ name: 'dybj', type: 'int' },
		{ name: 'hcbj', type: 'int' },
		{ name: 'rkdh', type: 'float' },
		{ name: 'rkxh', type: 'float' },
		{ name: 'tzdh', type: 'float' },
		{ name: 'htbh', type: 'float' },
		{ name: 'htxh', type: 'float' },
		{ name: 'rkrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'csbh' },
		{ name: 'yhbh' },
		{ name: 'csmc' },
		{ name: 'clhh' },
		{ name: 'clth' },
		{ name: 'clmc' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'khxh' },
		{ name: 'cpmc' },
		{ name: 'zcpmc' },
		{ name: 'jhbz' },
		{ name: 'jldw' },
		{ name: 'hwbh' },
		{ name: 'pcbh' },
		{ name: 'ghpc' },
		{ name: 'rksl', type: 'float' },
		{ name: 'cbdj', type: 'float' },
		{ name: 'rkdj', type: 'float' },
		{ name: 'rkje', type: 'float' },
		{ name: 'zzsl', type: 'float' },
		{ name: 'csdj', type: 'float' },
		{ name: 'csje', type: 'float' },
		{ name: 'zzse', type: 'float' },
		{ name: 'wbbh' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbdj', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'fzdw' },
		{ name: 'fzsl', type: 'float' },
		{ name: 'xdzl', type: 'float' },
		{ name: 'rklb', type: 'float' },
		{ name: 'rklbmc'},
		{ name: 'wkjq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jhrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'shsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zzrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'pjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'dysj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'dhh' },
		{ name: 'hth' },
		{ name: 'bzbh', type: 'float' },
		{ name: 'cgym' },
		{ name: 'cglx' },
		{ name: 'cgh' },
		{ name: 'glht', type: 'float' },
		{ name: 'zjhh' },
		{ name: 'jhh' },
		{ name: 'wxh' },
		{ name: 'sqh' },
		{ name: 'shdh' },
		{ name: 'fgh' },
		{ name: 'fgcp' },
		{ name: 'bzsm' },
		{ name: 'sxdy09' },
		{ name: 'jkrm' },
		{ name: 'czym' },
		{ name: 'sdrm' },
		{ name: 'glllh' },
		{ name: 'gltlh' },
		{ name: 'ycrk', type: 'int' },
		{ name: 'zlcsbh' },//专利付费厂商
		{ name: 'zldj',type: 'float'},//专利单价
		{ name: 'zlje',type: 'float'},//专利金额
		{ name: 'zlcsmc' },//专利付费厂商名称
		{ name: 'fphm'},
		{ name: 'cgyxm'},
		{ name: 'lbmc'},
		{ name: 'yfbj', type: 'int' }
	]
});
