Ext.define('erp.materialInventory.model.QueryParams', {
	extend: 'Ext.data.Model',
	fields: [		
		{ name: 'checkbox_rkdh' },
		{ name: 'rkdh1' },
		{ name: 'rkdh2' },
		{ name: 'checkbox_rkrq' },
		{ name: 'rkrq1' },
		{ name: 'rkrq2' },
		{ name: 'checkbox_csbh' },
		{ name: 'csbh' },
		{ name: 'checkbox_clmc' },
		{ name: 'clmc' },
		{ name: 'checkbox_htbh' },
		{ name: 'htbh1' },
		{ name: 'htbh2' }, 
		{ name: 'checkbox_dhdh' },
		{ name: 'dhdh1' },
		{ name: 'dhdh2' },		
		{ name: 'checkbox_rklb' },
		{ name: 'rklb' },		
		{ name: 'checkbox_wgbj' },
		{ name: 'wgbj' },		
		{ name: 'checkbox_hwbh' },
		{ name: 'hwbh' },
		{ name: 'checkbox_hth' },
		{ name: 'hth1' },
		{ name: 'hth2' },		
		{ name: 'checkbox_pcbh' },
		{ name: 'pcbh' },
		{ name: 'checkbox_jhh' },
		{ name: 'jhh' },
		{ name: 'checkbox_zzrq' },
		{ name: 'zzrq1' },
		{ name: 'zzrq2' },		
		{ name: 'checkbox_bzsm'},
		{ name: 'bzsm' },	
		{ name: 'checkbox_czsjdysj'},
		{ name: 'checkbox_ycrk'},
		{ name: 'ycrk'}
	]
});