Ext.define('erp.view.master.purchaseDetail.model.BomChangeSearch', {
	extend: 'Ext.data.Model',
	fields: [
		{ name: 'gzdh', type: 'int' },
		{ name: 'gzxh', type: 'int' },
		{ name: 'jlxh', type: 'int' },
		{ name: 'cpbh' },
		{ name: 'cptx1' },
		{ name: 'cptx2' },
		{ name: 'cptx3' },
		{ name: 'bbbh' },
		{ name: 'jgbh' },
		{ name: 'jgsx', type: 'float' },
		{ name: 'xnbj', type: 'int' },
		{ name: 'mjbz', type: 'int' },
		{ name: 'xqbj', type: 'int' },
		{ name: 'dybj', type: 'int' },
		{ name: 'thcl' },
		{ name: 'thtx1' },
		{ name: 'thtx2' },
		{ name: 'thtx3' },
		{ name: 'lbbh' },
		{ name: 'bjbb' },
		{ name: 'clhh' },
		{ name: 'clmc' },
		{ name: 'jldw' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'wzdh' },
		{ name: 'djyl', type: 'float' },
		{ name: 'clyl', type: 'float' },
		{ name: 'zhxs', type: 'float' },
		{ name: 'fzdw' },
		{ name: 'fzyl', type: 'float' },
		{ name: 'csbh' },
		{ name: 'gxbh' },
		{ name: 'bzsm' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gzzt', type: 'int' },
		{ name: 'xnjbh' },
		{ name: 'xnmc' },
		{ name: 'jhh' },
		{ name: 'clth' },
		{ name: 'fzzbj', type: 'int' },
		{ name: 'plmth' },
		{ name: 'plmtx' },
		{ name: 'jhsl', type: 'float' },
		{ name: 'cllbmc' },
		{ name: 'gxmc' }
	]
});
