Ext.define('erp.view.master.purchaseDetail.model.ContractDetail', {
	extend: 'Ext.data.Model',
	idProperty: 'htxh',
	fields: [
		{ name: 'htbh', type: 'float' },
		{ name: 'htxh', type: 'float' },
		{ name: 'clhh' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'jhlb' },
		{ name: 'jldw' },
		{ name: 'cgsl', type: 'float' },
		{ name: 'ycgl', type: 'float' },
		{ name: 'cgdj', type: 'float' },
		{ name: 'zzsl', type: 'float' },
		{ name: 'kzdj', type: 'float' },
		{ name: 'cgje', type: 'float' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbbh' },
		{ name: 'wbdj', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'cgrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'ghzq', type: 'float' },
		{ name: 'jhrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'hqjq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'ddbh', type: 'float' },
		{ name: 'ddxh', type: 'float' },
		{ name: 'jhbh', type: 'float' },
		{ name: 'jhxh', type: 'float' },
		{ name: 'zxhtbh', type: 'float' },
		{ name: 'zxhtxh', type: 'float' },
		{ name: 'cgbh', type: 'float' },
		{ name: 'cgxh', type: 'float' },
		{ name: 'sgbh' },
		{ name: 'sgxh', type: 'float' },
		{ name: 'sdck' },
		{ name: 'bzsm' },
		{ name: 'hsbm' },
		{ name: 'xzbj', type: 'float' },
		{ name: 'wkjq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gxsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jhh' },
		{ name: 'ddh' },
		{ name: 'cgh' },
		{ name: 'sgh' },
		{ name: 'zxhth' },
		{ name: 'clth' },
		{ name: 'clmc' },
		{ name: 'zzhxs', type: 'float' },
		{ name: 'fzdw' },
		{ name: 'fzsl', type: 'float' },
		{ name: 'fzkj', type: 'float' },
		{ name: 'fzzbj', type: 'float' },
		{ name: 'txgz' },
		{ name: 'sqbh', type: 'float' },
		{ name: 'sqxh', type: 'float' },
		{ name: 'sqh' },
		{ name: 'csxs1', type: 'float' },
		{ name: 'csxs2', type: 'float' },
		{ name: 'csxs3', type: 'float' },
		{ name: 'csxs4', type: 'float' },
		{ name: 'csxs5', type: 'float' },
		{ name: 'csxs6', type: 'float' },
		{ name: 'csxs7', type: 'float' },
		{ name: 'csxs8', type: 'float' },
		{ name: 'csjg', type: 'float' },
		{ name: 'kjlx', type: 'float' },
		{ name: 'htbz' },
		{ name: 'cjsl', type: 'float' },
		{ name: 'khbh' },
		{ name: 'cpbh' },
		{ name: 'pxxh', type: 'float' },
		{ name: 'wxbj', type: 'float' },
		{ name: 'ysgg' },
		{ name: 'dgyl' },
		{ name: 'dlgs', type: 'float' },
		{ name: 'rksl', type: 'float' },
		{ name: 'ggcs', type: 'float' },
		{ name: 'clbz' },
		{ name: 'zzlx' },
		{ name: 'zzyx' },
		{ name: 'zzbj', type: 'float' },
		{ name: 'zzrm' },
		{ name: 'zzsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'mxzs', type: 'float' },
		{ name: 'cpxj' },
		{ name: 'bzxx' },
		{ name: 'scbj', type: 'float' },
		{ name: 'cjjhrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'pzqrbj', type: 'float' },
		{ name: 'pzqrrm' },
		{ name: 'pzqrsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'psjq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'cfbj', type: 'float' },
		{ name: 'mjh' },
		{ name: 'cfbh', type: 'float' },
		{ name: 'cfxh', type: 'float' },
		{ name: 'cfh' },
		{ name: 'fach' },
		{ name: 'khxh' },
		{ name: 'ywms' },
		{ name: 'pono' },
		{ name: 'xmsjbc' },
		{ name: 'xjqrbj', type: 'float' },
		{ name: 'hsbmmc' },
		{ name: 'khjc' },
		{ name: 'ckmc' },
		{ name: 'cpmc'},
		{ name:'zldj', type: 'float' ,hidden:true},
		{ name:'requestid' }
	]
});
