Ext.define('erp.view.master.purchaseDetail.model.OutSourceDetail', {
	extend: 'Ext.data.Model',
	idProperty: 'wxxh',
	fields: [
		{ name: 'wxdh', type: 'float' },
		{ name: 'wxxh', type: 'float' },
		{ name: 'jhbh', type: 'float' },
		{ name: 'jhxh', type: 'float' },
		{ name: 'jhh' },
		{ name: 'cgbh', type: 'float' },
		{ name: 'cgxh', type: 'float' },
		{ name: 'cgh' },
		{ name: 'cpbh' },
		{ name: 'jldw' },
		{ name: 'tcsl', type: 'float' },
		{ name: 'jsbl', type: 'float' },
		{ name: 'jgsl', type: 'float' },
		{ name: 'jgdj', type: 'float' },
		{ name: 'jgje', type: 'float' },
		{ name: 'clhh' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'clmc' },
		{ name: 'ytcs', type: 'float' },
		{ name: 'sqbh', type: 'float' },
		{ name: 'sqxh', type: 'float' },
		{ name: 'sqh' },
		{ name: 'kzdj', type: 'float' },
		{ name: 'kjlx', type: 'int' },
		{ name: 'fzdw' },
		{ name: 'fzsl', type: 'float' },
		{ name: 'hqbj', type: 'int' },
		{ name: 'hqrm' },
		{ name: 'hqsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'wkjq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gxsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'dhrk', type: 'float' },
		{ name: 'rksl', type: 'float' }
	]
});
