Ext.define('erp.view.master.purchaseDetail.model.PurchaseDetailSearch', {
	extend: 'Ext.data.Model',
	fields: [
		{ name: 'topping1' ,type: 'boolean', defaultValue: false},
		{ name: 'cgh' },
		{ name: 'cghw' },
		{ name: 'topping2' ,type: 'boolean', defaultValue: false},
		{ name: 'clmc' },
		{ name: 'topping3' ,type: 'boolean', defaultValue: false},
		{ name: 'csmc' },
		{ name: 'topping4' ,type: 'boolean', defaultValue: false},
		{ name: 'cgym' },
		{ name: 'topping5' ,type: 'boolean', defaultValue: false},
		{ name: 'wcbj' },
		{ name: 'topping6' ,type: 'boolean', defaultValue: false},
		{ name: 'qfbj' },
		{ name: 'topping7' ,type: 'boolean', defaultValue: false},
		{ name: 'spbj' },
		{ name: 'topping8' ,type: 'boolean', defaultValue: false},
		{ name: 'hyhm' },
		{ name: 'topping9' ,type: 'boolean', defaultValue: false},
		{ name: 'jhlb' },
		{ name: 'topping10' ,type: 'boolean', defaultValue: false},
		{ name: 'jhh' },
		{ name: 'jhhw' },
		{ name: 'topping11' ,type: 'boolean', defaultValue: false},
		{ name: 'cgrq', type: 'date', dateFormat: 'Y.m.d H:i:s'},
		{ name: 'cgrqw', type: 'date', dateFormat: 'Y.m.d H:i:s'},
		{ name: 'topping12' ,type: 'boolean', defaultValue: false},
		{ name: 'jhrq', type: 'date', dateFormat: 'Y.m.d H:i:s'},
		{ name: 'jhrqw', type: 'date', dateFormat: 'Y.m.d H:i:s'},
		{ name: 'topping13' ,type: 'boolean', defaultValue: false},
		{ name: 'sxrq', type: 'date', dateFormat: 'Y.m.d H:i:s'},
		{ name: 'sxrqw', type: 'date', dateFormat: 'Y.m.d H:i:s'},
		{ name: 'jhqf' ,type: 'boolean', defaultValue: false},
		{ name: 'htqf' ,type: 'boolean', defaultValue: false},
		{ name: 'topping16' ,type: 'boolean', defaultValue: false},
		{ name: 'cllb' },
		{ name: 'topping14' ,type: 'boolean', defaultValue: false}
	]
});
