Ext.define('erp.arrivalRegister.model.Rkd', {
	extend: 'Ext.data.Model',
	idProperty: 'rkh',
	fields: [
	  {name : 'ckbh'},
	  {name : 'wbbh'},
	  {name : 'czym'},
	  {name : 'csmc'},
	  {name : 'sdrm'},
	  {name : 'jkrm'},
	  {name : 'bzsm'},
	  {name : 'clmc'},
	  {name : 'fzhm'},
	  {name : 'csbh'},
	  {name : 'clhh'},
	  {name : 'cltx1'},
	  {name : 'cltx2'},
	  {name : 'cltx3'},
	  {name : 'jldw'},
	  {name : 'hwbh'},
	  {name : 'pcbh'},
	  {name : 'ghpc'},
	  {name : 'yhbh'},
	  {name : 'sjly'},
	  {name : 'fzdw'},
	  {name : 'rklb'},
	  {name : 'cpmc'},
	  {name : 'hxrm'},
	  {name : 'cgym'},
	  {name : 'hth'},
	  {name : 'wxh'},
	  {name : 'fyxz'},
	  {name : 'cybh'},
	  {name : 'plmth'},
	  {name : 'plmtx'},
	  {name : 'ckmc'},
	  {name : 'shdh'},
	  {name : 'fplb'},
	  {name : 'fphm'},
	  {name : 'cgyxm'},
	  {name : 'cglbmc'},
	  {name : 'rklbmc'},
	  {name: 'dhrq',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name: 'hxrq',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name: 'hxsj',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name: 'shsj',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name: 'czsj',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name: 'sdsj',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name: 'dysj',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name: 'zzrq',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name: 'rkrq',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name: 'pjrq',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name : 'tjbj',type : 'int'},
	  {name : 'hzbj',type : 'int'},
	  {name : 'cfxh',type : 'float'},
	  {name : 'zzsl_hx',type : 'float'},
	  {name : 'zzsl',type : 'float'},
	  {name : 'wxdh',type : 'int'},
	  {name : 'wxxh',type : 'int'},
	  {name : 'tjdh',type : 'int'},
	  {name : 'hxbj',type : 'int'},
	  {name : 'rkdh',type : 'int'},
	  {name : 'rkxh',type : 'int'},
	  {name : 'cgsl',type : 'int'},
	  {name : 'dhsl',type : 'int'},
	  {name : 'rksl',type : 'int'},
	  {name : 'tzdh',type : 'int'},
	  {name : 'glht',type : 'int'},
	  {name : 'cgbh',type : 'int'},
	  {name : 'cgh'},
	  {name : 'cgxh',type : 'int'},
	  {name : 'htbh',type : 'int'},
	  {name : 'htxh',type : 'int'},
	  {name : 'hcdh',type : 'int'},
	  {name : 'hcxh',type : 'int'},
	  {name : 'sdbj',type : 'int'},
	  {name : 'dybj',type : 'int'},
	  {name : 'hcbj',type : 'int'},
	  {name : 'wgbj',type : 'int'},
	  {name : 'wxbj',type : 'int'},
	  {name : 'zsbj',type : 'int'},
	  {name : 'gjbj',type : 'int'},
	  {name : 'jzzt',type : 'int'},
	  {name : 'cglb'},
	  {name : 'xzbj',type : 'int'},
	  {name : 'scbj',type : 'int'},
	  {name : 'fzsl',type: 'float'},
	  {name : 'jgje',type: 'float'},
	  {name : 'rkdj',type: 'float'},
	  {name : 'rkje',type: 'float'},
	  {name : 'csdj',type: 'float'},
	  {name : 'csje',type: 'float'},
	  {name : 'zzse',type: 'float'},
	  {name : 'jhbh',type: 'float'},
	  {name : 'jhxh',type: 'float'},
	  {name : 'dhdh',type: 'float'},
	  {name : 'dhxh',type: 'float'},
	  {name : 'fzdj',type: 'float'},
	  {name : 'cpbh'},
	  {name : 'clje',type: 'float'},
	  {name : 'wxjgje',type: 'float'},
	  {name : 'wbhl',type: 'float'},
	  {name : 'wbdj',type: 'float'},
	  {name : 'wbje',type: 'float'},
	  {name:'rkh',convert:function(v,rec){
	  	return rec.get('rkdh')+'-'+rec.get('rkxh')
	  }}
	]
});
