Ext.define('erp.materialQualityTesting.model.CreateLead', {
	extend: 'Ext.data.Model',
	fields: [
		{ name: 'xzbj', type: 'int' },
		{ name: 'dybj', type: 'int' },
		{ name: 'wxbj', type: 'int' },
		{ name: 'jjbj', type: 'int' },
		{ name: 'shbj', type: 'int' },
		{ name: 'dhh' },
		{ name: 'ckbh' },
		{ name: 'ckmc' },
		{ name: 'ztmc' },
		{ name: 'czym' },
		{ name: 'shdh' },
		{ name: 'ztbj', type: 'int' },
		{ name: 'zjbj', type: 'int' },
		{ name: 'htbh', type: 'int' },
		{ name: 'htxh', type: 'int' },
		{ name: 'jhbh', type: 'int' },
		{ name: 'jhxh', type: 'int' },
		{ name: 'jyjg', type: 'int' },
		{ name: 'dhdh', type: 'float' },
		{ name: 'dhxh', type: 'float' },
		{ name: 'yrsl', type: 'float' },
		{ name: 'wrsl', type: 'float' },
		{ name:'dhh'},
		{ name: 'wtdh' },
		{ name: 'dhrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'pjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'qsrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jsrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'lbmc' },
		{ name: 'clhh' },
		{ name: 'clth' },
		{ name: 'clmc' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'jldw' },
		{ name: 'pcbh' },
		{ name: 'ghpc' },
		{ name: 'dhsl', type: 'float' },
		{ name: 'fzdw' },
		{ name: 'fzsl', type: 'float' },
		{ name: 'dpyy' },
		{ name: 'zjbz' },
		{ name: 'bzsm' },
		{ name: 'csbh' },
		{ name: 'csmc' },
		{ name: 'hth' },
		{ name: 'wxh' },
		{ name: 'jhh' },
		{ name: 'cpbh' },
		{ name: 'zcpmc' },
		{ name: 'jhbz' },
		{ name: 'sxrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zzjl' },
		{ name: 'zjdh' },
		{ name: 'zjrm' },
		{ name: 'zjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'shrm' },
		{ name: 'shsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'shjg' },
		{ name: 'shsm' },
		{ name: 'khbh' },
		{ name: 'khxh' },
		{ name: 'jkrm' },
		{ name: 'lbbh' }
	]
});
