Ext.define('erp.PurchaseCostDetial.model.PurchaseCostDetial', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'fydh', type: 'float' },
		{ name: 'fyxh', type: 'float' },
		{ name: 'fyrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'yhbh' },
		{ name: 'cglb' },
		{ name: 'csbh' },
		{ name: 'fyzy' },
		{ name: 'fysl', type: 'float' },
		{ name: 'fydj', type: 'float' },
		{ name: 'fyje', type: 'float' },
		{ name: 'fylb' },
		{ name: 'jhbh', type: 'float' },
		{ name: 'jhxh', type: 'float' },
		{ name: 'bzsm' },
		{ name: 'hxbj', type: 'int' },
		{ name: 'hxrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'fplb' },
		{ name: 'fplbmc' },
		{ name: 'fphm' },
		{ name: 'sdbj', type: 'int' },
		{ name: 'jzzt', type: 'int' },
		{ name: 'sdrm' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tzdh', type: 'float' },
		{ name: 'cfxh', type: 'float' },
		{ name: 'zzse', type: 'float' },
		{ name: 'fzhm' },
		{ name: 'htbh', type: 'float' },
		{ name: 'htxh', type: 'float' },
		{ name: 'fybz' },
		{ name: 'zzsl', type: 'float' },
		{ name: 'csdj', type: 'float' },
		{ name: 'csje', type: 'float' },
		{ name: 'hsbm' },
		{ name: 'spyj' },
		{ name: 'spsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tjbj', type: 'int' },
		{ name: 'tjrm' },
		{ name: 'tjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tjdx' },
		{ name: 'cybh' },
		{ name: 'fylx' },
		{ name: 'fyxz' },
		{ name: 'wbbh' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'jlxh', type: 'float' },
		{ name: 'ckbh' },
		{ name: 'xslb' },
		{ name: 'fyxs', type: 'float' },
		{ name: 'zflb' },
		{ name: 'cglx', type: 'int' },
		{ name: 'csmc' },
		{ name: 'bmmc' },
		{ name: 'wbdh' },
		{ name: 'xslbmc' },
		{ name: 'zflbmc' },
		{ name: 'sjzflbmc' },
		{ name: 'ssbmmc' },
		{ name: 'yhjc' },
		{ name: 'jhh' },
		{ name: 'hth' },
		{ name: 'rwh' },
	]
});
