Ext.define('erp.master.caterialPricePurchase.model.CaterialPricePurchase', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'clhh' },
		{ name: 'lbbh' },
		{ name: 'clmc' },
		{ name: 'jldw' },
		{ name: 'zhxs', type: 'float' },
		{ name: 'yshh' },
		{ name: 'ysmc' },
		{ name: 'cbdj', type: 'float' },
		{ name: 'jhdj', type: 'float' },
		{ name: 'kzdj', type: 'float' },
		{ name: 'fzkj', type: 'float' },
		{ name: 'cgbl', type: 'float' },
		{ name: 'ylbl', type: 'float' },
		{ name: 'shbl', type: 'float' },
		{ name: 'yxqx', type: 'float' },
		{ name: 'ghzq', type: 'float' },
		{ name: 'cgtqq', type: 'float' },
		{ name: 'zjbj', type: 'int' },
		{ name: 'cgbj', type: 'int' },
		{ name: 'aqlbj', type: 'int' },
		{ name: 'yhyl', type: 'float' },
		{ name: 'clth' },
		{ name: 'cgym' },
		{ name: 'bzsm' },
		{ name: 'bcpbj', type: 'int' },
		{ name: 'bcpbh' },
		{ name: 'bcplb' },
		{ name: 'cltp' },
		{ name: 'gdbj', type: 'int' },
		{ name: 'sqrm' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'lkcbj', type: 'int' },
		{ name: 'bmgz' },
		{ name: 'fzzbj', type: 'int' },
		{ name: 'zhbj', type: 'int' },
		{ name: 'zhgs', type: 'float' },
		{ name: 'txgz' },
		{ name: 'gsbh', type: 'float' },
		{ name: 'spbj_kj', type: 'int' },
		{ name: 'yzws', type: 'int' },
		{ name: 'djyz', type: 'int' },
		{ name: 'cgzh' },
		{ name: 'free', type: 'int' },
		{ name: 'yxbj', type: 'int' },
		{ name: 'gdrm' },
		{ name: 'gdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jjczym' },
		{ name: 'jjczsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'qssxsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jzsxsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gxbh' },
		{ name: 'hbdj', type: 'float' },
		{ name: 'scys', type: 'float' },
		{ name: 'clzc', type: 'float' },
		{ name: 'sprm_kj' },
		{ name: 'spsj_kj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gjfdxs', type: 'float' },
		{ name: 'plmtx' },
		{ name: 'gsmc'},
		{ name: 'fzdw'},
		{ name: 'zdcgl', type: 'float' },
		{ name: 'zxbzl', type: 'float' }
	]
});
