Ext.define('erp.express.model.Production', {
	extend: 'erp.common.basic.model.Model',
	idProperty: 'cpbh',
	fields: [
		{ name: 'cpbh' },
		{ name: 'lbbh' },
		{ name: 'cpmc' },
		{ name: 'jldw' },
		{ name: 'ysbh' },
		{ name: 'ysmc' },
		{ name: 'bzdj', type: 'float' },
		{ name: 'jhdj', type: 'float' },
		{ name: 'bzgs', type: 'float' },
		{ name: 'yxqx', type: 'float' },
		{ name: 'sczq', type: 'float' },
		{ name: 'mxzs', type: 'float' },
		{ name: 'xtcd', type: 'float' },
		{ name: 'xtkd', type: 'float' },
		{ name: 'xtgd', type: 'float' },
		{ name: 'mxtj', type: 'float' },
		{ name: 'mxmz', type: 'float' },
		{ name: 'mxjz', type: 'float' },
		{ name: 'cpjz', type: 'float' },
		{ name: 'cpth' },
		{ name: 'bzsm' },
		{ name: 'cprz' },
		{ name: 'rzxh' },
		{ name: 'zbbh', type: 'float' },
		{ name: 'mcxs', type: 'float' },
		{ name: 'ddcs', type: 'float' },
		{ name: 'mtsl', type: 'float' },
		{ name: 'cg20', type: 'float' },
		{ name: 'pg40', type: 'float' },
		{ name: 'cg40', type: 'float' },
		{ name: 'cg45', type: 'float' },
		{ name: 'bcpbj', type: 'int' },
		{ name: 'bcpbh' },
		{ name: 'cptp' },
		{ name: 'gdbj', type: 'int' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bmgz' },
		{ name: 'qfbj' },
		{ name: 'spbj', type: 'int' },
		{ name: 'sprm' },
		{ name: 'spsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'ycpbh' },
		{ name: 'cpmc_yw' },
		{ name: 'sclx' },
		{ name: 'gxsd', type: 'int' },
		{ name: 'sdrm' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bomlb' },
		{ name: 'jhlbh' },
		{ name: 'hsbm' },
		{ name: 'bgywm' },
		{ name: 'bgzwm' },
		{ name: 'cpms_yw' },
		{ name: 'khxh' },
		{ name: 'tcgx' },
		{ name: 'fach' },
		{ name: 'yfbm' },
		{ name: 'bgys' },
		{ name: 'wmbh', type: 'float' },
		{ name: 'gdrm' },
		{ name: 'gdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zjbj', type: 'int' },
		{ name: 'scbj', type: 'int' },
		{ name: 'shbj', type: 'int' },
		{ name: 'shrm' },
		{ name: 'shsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bzjbj', type: 'int' }
	]
});
