Ext.define('erp.express.model.Shipment', {
	extend: 'erp.common.basic.model.Model',
	idProperty: 'cybh',
	fields: [
		{ name:'tablename',defaultValue:'cyjhb'}, //出运计划表
		{ name: 'cybh' },
		{ name: 'xslb' },
		{ name: 'wtbh' },
		{ name: 'khbh' },
		{ name: 'yslx' },
		{ name: 'yhrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'chsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'cysj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'ywym' },
		{ name: 'ywzg' },
		{ name: 'bzsm' },
		{ name: 'gcjq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'sfpx' },
		{ name: 'ckxb' },
		{ name: 'yhbj' },
		{ name: 'yfshbj', type: 'int' },
		{ name: 'gdbj', type: 'int' },
		{ name: 'gdrm' },
		{ name: 'gdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jzbj', type: 'int' },
		{ name: 'chzs', type: 'float' },
		{ name: 'sfzs', type: 'float' },
		{ name: 'yfje', type: 'float' },
		{ name: 'chyq' },
		{ name: 'fkxx' },
		{ name: 'fphm' },
		{ name: 'fpdm' },
		{ name: 'hxdh' },
		{ name: 'xyzh' },
		{ name: 'qygc' },
		{ name: 'dcsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'lcsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bgtsbz' },
		{ name: 'bgfprq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bgxdrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'cyfs' },
		{ name: 'gjsl', type: 'float' },
		{ name: 'kztj', type: 'float' },
		{ name: 'cydw' },
		{ name: 'cyym' },
		{ name: 'pglt' },
		{ name: 'tydw_yf' },
		{ name: 'lxdz_eng' },
		{ name: 'tdhm' },
		{ name: 'qtdz' },
		{ name: 'jzry' },
		{ name: 'psbj', type: 'int' },
		{ name: 'pssj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'psrm' },
		{ name: 'qfbj', type: 'int' },
		{ name: 'qfsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'qfrm' },
		{ name: 'wcbj', type: 'int' },
		{ name: 'fkbj', type: 'int' },
		{ name: 'sjbj', type: 'int' },
		{ name: 'sjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'sjrm' },
		{ name: 'fdbj', type: 'int' },
		{ name: 'fdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'fdrm' },
		{ name: 'yjbj', type: 'int' },
		{ name: 'yjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'yjrm' },
		{ name: 'shrm' },
		{ name: 'shsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'shbj', type: 'int' },
		{ name: 'sdbj', type: 'int' },
		{ name: 'sdrm' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'qrbj', type: 'int' },
		{ name: 'qrrm' },
		{ name: 'qrsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tjbj', type: 'int' },
		{ name: 'tjrm' },
		{ name: 'tjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tjysbj', type: 'int' },
		{ name: 'tjysrm' },
		{ name: 'tjyssj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bgshbj', type: 'int' },
		{ name: 'tdqrbj', type: 'int' },
		{ name: 'tdqrrm' },
		{ name: 'tdqrsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tdbzsm' },
		{ name: 'cyshrm' },
		{ name: 'cyshsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'cyshbj', type: 'int' },
		{ name: 'jzxcybj', type: 'int' },
		{ name: 'jzxcyrm' },
		{ name: 'jzxcysj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'cwtjbj', type: 'int' },
		{ name: 'cwtjrm' },
		{ name: 'cwtjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'djbj', type: 'int' },
		{ name: 'djsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'djrm' },
		{ name: 'clbj', type: 'int' },
		{ name: 'clrm' },
		{ name: 'clsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zxqrbj', type: 'int' },
		{ name: 'zxqrrm' },
		{ name: 'zxqrsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czrm' },
		{ name: 'scbj', type: 'int' },
		{ name: 'drpycbj', type: 'int' },
		{ name: 'tdgdbj', type: 'int' },
		{ name: 'tdgdrm' },
		{ name: 'tdgdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bgze', type: 'float' },
		{ name: 'yfze', type: 'float' },
		{ name: 'zdkh' },
		{ name: 'cfd' },//出货地
		{ name:'khmc'},
		{name: 'mzzz', type: 'float'},//箱毛重
		{name: 'jzzz', type: 'float'},//箱净重
		{name: 'xshj', type: 'int'},//货物总箱数
		{name: 'tjhj', type: 'float'},//货物总体积
		{ name:'gdhm'},
		{ name:'cmhc'},
		{ name:'hdzmm'}, //货代公司名称
		{ name:'ysgsmc'}, //运输公司名
		{ name:'kcrq',type: 'date', dateFormat: 'Y-m-d H:i:s'},//开船日期
		{ name:'ywyzg'},//业务员主管
		{ name:'xslbmc'},//销售类别名称
		{ name:'ywymc'},
		{ name:'hdmc'}, //货代名称
		{ name:'ysgs'},  //运输公司
		{ name:'zkmybj'},
		{name:'bgpc'},
		{ name:'htbh'},
		{name:'bgrm'}
	]
});
