Ext.define('erp.view.purchaseUrge.model.MainSearch', {
	extend: 'Ext.data.Model',
	fields: [
		{ name: 'htbh' },
		{ name: 'htbhw' },
		{ name: 'csmc' },
		{ name: 'clmc' },
		{ name: 'jhrq', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name: 'jhrqw', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name: 'jzrq', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name: 'jzrq2', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name: 'hqjq', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name: 'hqjqw', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name: 'rwsx', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name: 'rwsxw', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name:'wkjq', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name:'wkjqw', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name:'qrjq', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name:'qrjqw', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name: 'jhbz' },
		{ name: 'jhh' },
		{ name: 'cgh' },
		{ name: 'cgym' },
		{ name: 'x_wlzbcx' ,type: 'boolean', defaultValue: false},
		{ name: 'x_wkww' ,type: 'boolean', defaultValue: false},
		{ name: 'x_wkwwyz' ,type: 'boolean', defaultValue: false},
		{ name: 'x_wkjqyc' ,type: 'boolean', defaultValue: false},
		{ name: 'x_cjqfrq' ,type: 'boolean', defaultValue: false},
		{ name: 'x_wkjqbd' ,type: 'boolean', defaultValue: false},
		{ name: 'topping12' ,type: 'boolean', defaultValue: false},
		{ name: 'topping11' ,type: 'boolean', defaultValue: false},
		{ name: 'topping10' ,type: 'boolean', defaultValue: false},
		{ name: 'topping9' ,type: 'boolean', defaultValue: false},
		{ name: 'topping1' ,type: 'boolean', defaultValue: false},
		{ name: 'topping3' ,type: 'boolean', defaultValue: false},
		{ name: 'topping4' ,type: 'boolean', defaultValue: false},
		{ name: 'topping5' ,type: 'boolean', defaultValue: false},
		{ name: 'topping6' ,type: 'boolean', defaultValue: false},
		{ name: 'topping7' ,type: 'boolean', defaultValue: false},
		{ name: 'topping8' ,type: 'boolean', defaultValue: false},
		{ name: 'topping2' ,type: 'boolean', defaultValue: false},
		{ name: 'topping13' ,type: 'boolean', defaultValue: false},
		{ name: 'topping14' ,type: 'boolean', defaultValue: false},
		{ name: 'topping15' ,type: 'boolean', defaultValue: false},
		{ name: 'topping16' ,type: 'boolean', defaultValue: false},
		{ name: 'topping17' ,type: 'boolean', defaultValue: false},
		{ name: 'czym' },
		{ name: 'khjc' }
	]
});
