Ext.define('erp.master.purchaseCost.model.MaterialEntrustImp', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'wtdh', type: 'float' },
		{ name: 'wtxh', type: 'float' },
		{ name: 'wtdj', type: 'float' },
		{ name: 'wtje', type: 'float' },
		{ name: 'wtbm' },
		{ name: 'wth' },
		{ name: 'hth' },
		{ name: 'hth' },
		{ name: 'dhh' },
		{ name: 'ddh' },
		{ name: 'wtrm' },
		{ name: 'csmc' },
		{ name: 'clmc' },
		{ name: 'khbh' },
		{ name: 'plmth' },
		{ name: 'plmtx' },
		{ name: 'csjgmc' },
		{ name: 'khbh' },
		{ name: 'wtrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'clhh' },
		{ name: 'htbh', type: 'float' },
		{ name: 'htxh', type: 'float' },
		{ name: 'csbh' },
		{ name: 'llrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'sjsl', type: 'float' },
		{ name: 'jldw' },
		{ name: 'sdbj', type: 'int' },
		{ name: 'xzbj', type: 'int' },
		{ name: 'sdrm' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jybj', type: 'int' },
		{ name: 'gdbj', type: 'int' },
		{ name: 'gdbj_pd', type: 'int' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'shbj', type: 'int' },
		{ name: 'ckbh' },
		{ name: 'dhdh', type: 'float' },
		{ name: 'dhxh', type: 'float' },
		{ name: 'bzsm' },
		{ name: 'jysj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'shsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'csmd' },
		{ name: 'csjg' },
		{ name: 'cslx' },
		{ name: 'qfbj', type: 'int' }
	]
});
