Ext.define('erp.master.purchaseCost.model.PurchaseCost', {
	extend: 'erp.common.basic.model.Model',
	idProperty: 'fyh',
	fields: [
		{ name: 'fydh', type: 'int' },
		{ name: 'fyxh', type: 'int' },
		{name:'fyh',convert:function(v,rec){
	  	return rec.get('fydh')+'-'+rec.get('fyxh')
	  }},
		{ name: 'fyrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'yhbh' },
		{ name: 'cglb' },
		{ name: 'csbh' },
		{ name: 'fyzy' },
		{ name: 'fysl', type: 'float' },
		{ name: 'fydj', type: 'float' },
		{ name: 'fyje', type: 'float' },
		{ name: 'fylb' },
		{ name: 'jhbh', type: 'float' },
		{ name: 'jhxh', type: 'float' },
		{ name: 'jfzl', type: 'float' },
		{ name: 'bzsm' },
		{ name: 'hxbj', type: 'int' },
		{ name: 'hxrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'fplb' },
		{ name: 'fphm' },
		{ name: 'sdbj', type: 'int' },
		{ name: 'sdrm' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tzdh', type: 'float' },
		{ name: 'cfxh', type: 'float' },
		{ name: 'fzhm' },
		{ name: 'htbh', type: 'float' },
		{ name: 'htxh', type: 'float' },
		{ name: 'zzsl', type: 'float' },
		{ name: 'csdj', type: 'float' },
		{ name: 'csje', type: 'float' },
		{ name: 'hsdh', type: 'float' },
		{ name: 'hsxh', type: 'float' },
		{ name: 'jfzl', type: 'float' },
		{ name: 'hsbm' },
		{ name: 'spbj', type: 'int' },
		{ name: 'kjbj', type: 'int' },
		{ name: 'fffs', type: 'int' },
		{ name: 'sprm' },
		{ name: 'spyj' },
		{ name: 'spsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tjbj', type: 'int' },
		{ name: 'tjrm' },
		{ name: 'tjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tjdx' },
		{ name: 'cybh' },
		{ name: 'fylx' },
		{ name: 'fpdx' },
		{ name: 'fyxz' },
		{ name: 'wbbh' },
		{ name: 'wbdh' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'wxdh', type: 'float' },
		{ name: 'wxxh', type: 'float' },
		{ name: 'shdh', type: 'float' },
		{ name: 'shxh', type: 'float' },
		{ name: 'dybj', type: 'int' },
		{ name: 'dysj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gxbh' },
		{ name: 'jlbh', type: 'float' },
		{ name: 'ycdh', type: 'float' },
		{ name: 'jlxh', type: 'float' },
		{ name: 'ckbh' },
		{ name: 'dbdh', type: 'float' },
		{ name: 'clwtdh', type: 'float' },
		{ name: 'clwtxh', type: 'float' },
		{ name: 'cpwtdh', type: 'float' },
		{ name: 'cpwtxh', type: 'float' },
		{ name: 'ysjldh_wms', type: 'float' },
		{ name: 'ysjlxh_wms', type: 'float' },
		{ name: 'zlrkdh', type: 'float' },
		{ name: 'zlrkxh', type: 'float' },
		{ name: 'zgfyxh', type: 'float' },
		{ name: 'fypc' },
		{ name: 'ftms' },
		{ name: 'zlckbh' },
		{ name: 'zrbm' },
		{ name: 'ftxs', type: 'float' },
		{ name: 'fsbm' },
		{ name: 'xslb' },
		{ name: 'fhdh', type: 'float' },
		{ name: 'fhxh', type: 'float' },
		{ name: 'fhck' },
		{ name: 'fhckmc' },
		{ name: 'gzdh' },
		{ name: 'gzxh', type: 'float' },
		{ name: 'mxzs', type: 'float' },
		{ name: 'fyxs', type: 'float' },
		{ name: 'zflb' },
		{ name: 'dcrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'dbxs', type: 'float' },
		{ name: 'ystj', type: 'float' },
		{ name: 'zyrm' },
		{ name: 'sgtzh' },
		{ name: 'zgbh', type: 'float' },
		{ name: 'zgxh', type: 'float' },
		{ name: 'xkxj' },
		{ name: 'cglx' },
		{ name: 'zzse', type: 'float'},
		{ name: 'sjfylb'},
		{ name: 'jhh'},
		{ name: 'rkh'},
		{ name: 'hth'},
		{ name: 'phh'},
		{ name: 'hsh'},
		{ name: 'wbdj', type:'float'},
		{ name: 'wxh'},
		{ name: 'ych'},
		{ name: 'dbh'},
		{ name: 'khbh'},
		{ name: 'khmc'},
		{ name: 'clwth'},
		{ name: 'cpwth'},
		{ name: 'csmc'},
		{ name: 'jhbz'},
		/*{ name: 'yfbj', type:'int'},*/
		{ name: 'bmmc'},
		{ name: 'sybm'},
		{ name: 'xslbmc'},
		{ name: 'zflbmc'},
		{ name: 'jhlbmc'},
		{ name: 'sjzflbmc'},
		{ name: 'scgxmc'},
		{ name: 'fybz'},
		{ name: 'fyslzh'},
		{ name: 'fyjezh'},
		{ name: 'csjezh'},
		{ name: 'sezh'},
		{ name: 'fkfs'},
		{ name: 'ztbh'}
	]
});
