Ext.define('erp.master.purchaseCost.model.TaskImp', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'rwdh', type: 'float' },
		{ name: 'rwxh', type: 'float' },
		{ name: 'jhbh', type: 'float' },
		{ name: 'jhxh', type: 'float' },
		{ name: 'cpbh' },
		{ name: 'jldw' },
		{ name: 'wxh' },
		{ name: 'jhh' },
		{ name: 'zyh' },
		{ name: 'zjh' },
		{ name: 'tcsl', type: 'float' },
		{ name: 'jsbl', type: 'float' },
		{ name: 'rwsl', type: 'float' },
		{ name: 'wcsl', type: 'float' },
		{ name: 'yrsl', type: 'float' },
		{ name: 'drsl', type: 'float' },
		{ name: 'jgje', type: 'float' },
		{ name: 'wcbj', type: 'int' },
		{ name: 'bzsm' },
		{ name: 'sjbj', type: 'int' },
		{ name: 'zybh', type: 'float' },
		{ name: 'zyxh', type: 'float' },
		{ name: 'bzgj', type: 'float' },
		{ name: 'sjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'wcrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gjxs', type: 'float' },
		{ name: 'jsdj', type: 'float' },
		{ name: 'jsbj', type: 'int' },
		{ name: 'kjbj', type: 'int' },
		{ name: 'jsrm' },
		{ name: 'csmc' },
		{ name: 'csbh' },
		{ name: 'cpmc' },
		{ name: 'gxbh' },
		{ name: 'jhlb' },
		{ name: 'jhlbmc' },
		{ name: 'plmth' },
		{ name: 'plmtx' },
		{ name: 'zcpbh' },
		{ name: 'zcpmc' },
		{ name: 'khmc' },
		{ name: 'gxmc' },
		{ name: 'jhbz' },
		{ name: 'cpth' },
		{ name: 'thbh' },
		{ name: 'jssj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'psmj', type: 'float' },
		{ name: 'fzhm' },
		{ name: 'fcsl', type: 'float' },
		{ name: 'sqbh', type: 'float' },
		{ name: 'sqxh', type: 'float' },
		{ name: 'flbz' },
		{ name: 'jssl', type: 'float' },
		{ name: 'zzbj', type: 'int' },
		{ name: 'zzrm' },
		{ name: 'zzrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zhdj', type: 'float' },
		{ name: 'fysl', type: 'float' }
	]
});
