Ext.define('erp.master.purchaseCost.model.TransportCostImp', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'jldh', type: 'float' },
		{ name: 'jlxh', type: 'float' },
		{ name: 'ysxs', type: 'float' },
		{ name: 'ystj', type: 'float' },
		{ name: 'ysdj', type: 'float' },
		{ name: 'ysje', type: 'float' },
		{ name: 'zccq' },
		{ name: 'zrcq' },
		{ name: 'cpbh' },
		{ name: 'cptx1' },
		{ name: 'cptx2' },
		{ name: 'cptx3' },
		{ name: 'jldw' },
		{ name: 'djlx' },
		{ name: 'djbh', type: 'float' },
		{ name: 'djxh', type: 'float' },
		{ name: 'ydsl', type: 'float' },
		{ name: 'ydje', type: 'float' },
		{ name: 'wdje', type: 'float' },
		{ name: 'wdsl', type: 'float' },
		{ name: 'llrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bzsm' },
		{ name: 'lxrm' },
		{ name: 'csbh' },
		{ name: 'csmc' },
		{ name: 'jlh' },
		{ name: 'xzbj',type: 'int' }
	]
});
