Ext.define('erp.view.master.purchaseDetail.model.MaterialDetail', {
	extend: 'Ext.data.Model',
	idProperty: 'clhh',
	fields: [
		//{ name:'tablename',defaultValue:'clbmb'}, //材料编码表
		{ name: 'clhh' },
		{ name: 'lbbh' },
		{ name: 'clmc' },
		{ name: 'jldw' },
		{ name: 'zhxs', type: 'float' },
		{ name: 'zzhxs', type: 'float' },
		{ name: 'bzxssx', type: 'float' },
		{ name: 'bzxsxx', type: 'float' },
		{ name: 'fzdw' },
		{ name: 'yshh' },
		{ name: 'ysmc' },
		{ name: 'cbdj', type: 'float' },
		{ name: 'jhdj', type: 'float' },
		{ name: 'kzdj', type: 'float' },
		{ name: 'fzkj', type: 'float' },
		{ name: 'zdcgl', type: 'float' },
		{ name: 'zxbzl', type: 'float' },
		{ name: 'cgbl', type: 'float' },
		{ name: 'ylbl', type: 'float' },
		{ name: 'shbl', type: 'float' },
		{ name: 'yxqx', type: 'int' },
		{ name: 'ghzq', type: 'int' },
		{ name: 'cgtqq', type: 'int' },
		{ name: 'zjbj', type: 'int' },
		{ name: 'cgbj', type: 'int' },
		{ name: 'aqlbj', type: 'int' },
		{ name: 'yhyl', type: 'float' },
		{ name: 'clth' },
		{ name: 'cgym' },
		{ name: 'bzsm' },
		{ name: 'bcpbj', type: 'int' },
		{ name: 'bcpbh' },
		{ name: 'bcplb' },
		{ name: 'cltp' },
		{ name: 'gdbj', type: 'int' },
		{ name: 'sqrm' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'lkcbj', type: 'int' },
		{ name: 'bmgz' },
		{ name: 'fzzbj', type: 'int' },
		{ name: 'zhbj', type: 'int' },
		{ name: 'zhgs', type: 'float' },
		{ name: 'txgz' },
		{ name: 'gsbh', type: 'int' },
		{ name: 'spbj', type: 'int' },
		{ name: 'sprm' },
		{ name: 'spsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'yzws', type: 'int' },
		{ name: 'djyz', type: 'int' },
		{ name: 'cgzh' },
		{ name: 'free', type: 'int' },
		{ name: 'yxbj', type: 'int' },
		{ name: 'gdrm' },
		{ name: 'gdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jjczym' },
		{ name: 'jjczsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'qssxsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jzsxsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gxbh' },
		{ name: 'hbdj', type: 'int' },
		{ name: 'scys', type: 'float' },
		{ name: 'clzc', type: 'float' },
		{ name: 'spbj_kj', type: 'int' },
		{ name: 'sprm_kj' },
		{ name: 'spsj_kj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gjfdxs', type: 'float' },
		{ name: 'rkdj', type: 'float' },
		{ name: 'htdj', type: 'float' },
		{ name:'pjbj',type:'int'},
		{ name: 'djyl', type: 'float' },
		{ name:'jgyl', type: 'float' },
		{ name:'jsbl',type:'float',convert:function(value,record){
			return 1+(record.get('shbl')/100);
		}},
		{ name:'tzll',type:'float'}
		/*{ name: 'fzyl', type: 'float' },
		{ name:'wzdh'},
		{ name:'bzjbj',type:'int'},
		{ naem:'px' ,type:'int'},
		{ name:'csmc'}*/
	]
});
