Ext.define('erp.master.materialArchive.model.Material', {
	extend: 'Ext.data.Model',
	idProperty: 'clhh',
	fields: [
		{ name: 'clhh' },
		{ name: 'lbbh' },
		{ name: 'lbmc' },
		{ name: 'clmc' },
		{ name: 'jldw' },
		{ name: 'yshh' },
		{ name: 'ysmc' },
		{ name: 'clth' },
		{ name: 'bcpbh' },
		{ name: 'cltp' },
		{ name: 'gdrm' },
		{ name: 'plmth' },
		{ name: 'plmtx' },
		{ name: 'cbdj', type: 'float' },
		{ name: 'zhxs', type: 'float' },
		{ name: 'jhdj', type: 'float' },
		{ name: 'kzdj', type: 'float' },
		{ name: 'fzkj', type: 'float' },
		{ name: 'cgbl', type: 'float' },
		{ name: 'ylbl', type: 'float' },
		{ name: 'shbl', type: 'float' },
		{ name: 'yxqx', type: 'float' },
		{ name: 'ghzq', type: 'float' },
		{ name: 'cgtqq', type: 'float' },
		{ name: 'zdcgl', type: 'float' },
		{ name: 'zxbzl', type: 'float' },
		{ name: 'yhyl', type: 'float' },
		{ name: 'bzxssx', type: 'float' },
		{ name: 'bzxsxx', type: 'float' },
		{ name: 'zzhxs', type: 'float' },
		{ name: 'zjbj', type: 'int' },
		{ name: 'cgbj', type: 'int' },
		{ name: 'cgym' },
		{ name: 'bcpbj', type: 'int' },
		{ name: 'gdbj', type: 'int' },
		{ name: 'sqrm' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'lkcbj', type: 'int' },
		{ name: 'zhbj', type: 'int' },
		{ name: 'zhgs', type: 'float' },
		{ name: 'scys', type: 'float' },
		{ name: 'clzc', type: 'float' },
		{ name: 'gsbh', type: 'float' },
		{ name: 'spbj', type: 'int' },
		{ name: 'sprm' },
		{ name: 'spsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'yzws', type: 'int' },
		{ name: 'djyz', type: 'int' },
		{ name: 'cgzh' },
		{ name: 'yxbj', type: 'int' },
		{ name: 'cgyxm'},
		{ name: 'aqlbj',type: 'int'},
		{ name: 'fzzbj',type: 'int'},
		{ name: 'zhgsmc'},
		{ name: 'txgz'},
		{ name: 'yygsmc'},
		{ name: 'cgzm'},
		{ name: 'txgzmc'},
		{ name: 'db_TYPE'}
	]
});
