Ext.define('erp.master.prematerial.model.Prematerial', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'ckbh' },
		{ name: 'dhdh', type: 'float' },
		{ name: 'dhxh', type: 'float' },
		{ name: 'dhrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'pjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'csbh' },
		{ name: 'clhh' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'pcbh' },
		{ name: 'ghpc' },
		{ name: 'dhsl', type: 'float' },
		{ name: 'yrsl', type: 'float' },
		{ name: 'jldw' },
		{ name: 'htbh', type: 'float' },
		{ name: 'htxh', type: 'float' },
		{ name: 'jhbh', type: 'float' },
		{ name: 'jhxh', type: 'float' },
		{ name: 'zzrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jkrm' },
		{ name: 'bzsm' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zjbj', type: 'int' },
		{ name: 'jjbj', type: 'int' },
		{ name: 'ztbj', type: 'int' },
		{ name: 'jyjg', type: 'int' },
		{ name: 'zjdh' },
		{ name: 'zjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zjbz' },
		{ name: 'dpyy' },
		{ name: 'dybj', type: 'int' },
		{ name: 'zjrm' },
		{ name: 'zjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'thdh', type: 'float' },
		{ name: 'thrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'thbj', type: 'int' },
		{ name: 'wxbj', type: 'int' },
		{ name: 'wxdh', type: 'float' },
		{ name: 'wxxh', type: 'float' },
		{ name: 'shdh' },
		{ name: 'fzsl', type: 'float' },
		{ name: 'fzdw' },
		{ name: 'hwbh' },
		{ name: 'shrm' },
		{ name: 'shsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'shjg' },
		{ name: 'shsm' },
		{ name: 'zzbj', type: 'int' },
		{ name: 'zzrm' },
		{ name: 'zzsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'shbj', type: 'int' },
		{ name: 'csmc'},
		{ name: 'clmc'},
		{ name: 'ztmc'},
		{ name: 'jlmc'},
		{ name:  'hth'},
		{ name:  'wxh'},
		{ name:  'ckmc'}
	]
});
