Ext.define('erp.master.prematerial.model.QueryParam', {
	extend: 'Ext.data.Model',
	fields: [		
	{ name: 'checkbox_id'},
	{ name: 'checkbox_dhdh'},
	{ name: 'dhdh1'},
	{ name: 'dhdh2'},
	{ name: 'checkbox_dhrq'},
	{ name: 'dhrq1'},
	{ name: 'dhrq2'},
	{ name: 'checkbox_csbh'},
	{ name: 'csmc'},
	{ name: 'checkbox_clmc'},
	{ name: 'clmc'},
	{ name: 'checkbox_ztbj'},
	{ name: 'ztbj'},
	{ name: 'checkbox_jyjg'},
	{ name: 'jyjg'},
	{ name: 'checkbox_zjdh'},
	{ name: 'zjdh1'},
	{ name: 'zjdh2'},
	{ name: 'checkbox_htbh'},
	{ name: 'htbh1'},
	{ name: 'htbh2'},
	{ name: 'checkbox_scpc'},
	{ name: 'scpc'},
	{ name: 'checkbox_bzsm'},
	{ name: 'bzsm'},
	{ name: 'checkbox_jlpp'},
	{ name: 'jlpp'},
	{ name: 'checkbox_ckbh'},
	{ name: 'ckbh'}
	]
});