Ext.define('erp.view.purchaseOrder.model.OutSourceDetailImp', {
	extend: 'Ext.data.Model',
	fields: [
		{ name: 'jhbh', type: 'int' },
		{ name: 'jhxh', type: 'int' },
		{ name: 'jlxh', type: 'int' },
		{ name: 'cpbh' },
		{ name: 'bbbh' },
		{ name: 'jgbh' },
		{ name: 'jgsx', type: 'int' },
		{ name: 'xnbj', type: 'int' },
		{ name: 'mjbz', type: 'int' },
		{ name: 'xqbj', type: 'int' },
		{ name: 'dybj', type: 'int' },
		{ name: 'lbbh' },
		{ name: 'bjbb' },
		{ name: 'clhh' },
		{ name: 'clmc' },
		{ name: 'jldw' },
		{ name: 'clth' },
		{ name: 'wzdh' },
		{ name: 'djyl', type: 'float' },
		{ name: 'clyl', type: 'float' },
		{ name: 'jhyl', type: 'float' },
		{ name: 'bcyl', type: 'float' },
		{ name: 'csbh' },
		{ name: 'bzsm' },
		{ name: 'px' },
		{ name: 'bj', type: 'int' },
		{ name: 'sx', type: 'int' },
		{ name: 'xzbj', type: 'int' },
		{ name: 'gxbh' },
		{ name: 'cltx1' },
		{ name: 'plmth' },
		{ name: 'plmtx' },
		{ name:'cllbmc'},
		{ name:'gxmc'},
		{ name:'shbl', type: 'float' }
	]
});
