Ext.define('erp.view.purchaseOrder.model.ProductDescImp', {
	extend: 'Ext.data.Model',
	fields: [
		{ name: 'ddh' ,header:'订单号',columnWidth:80},
		{ name: 'cpbh',header:'产品编号',columnWidth:80},
		{ name: 'cpth',header:'产品图号',columnWidth:80},
		{ name: 'cpmc',header:'产品名称',columnWidth:160},
		{ name: 'jldw',header:'单位',columnWidth:50},
		{ name: 'ddbh', type: 'int' ,hidden:true},
		{ name: 'ddxh', type: 'int' ,hidden:true},
		{ name: 'cptx1' ,hidden:true},
		{ name: 'cptx2' ,hidden:true},
		{ name: 'cptx3' ,hidden:true},
		{ name: 'dhsl', type: 'float',hidden:true },
		{ name: 'bssl', type: 'float',hidden:true },
		{ name: 'bzdj', type: 'float',hidden:true },
		{ name: 'xszk', type: 'float',hidden:true },
		{ name: 'xsdj', type: 'float',hidden:true },
		{ name: 'xsje', type: 'float',hidden:true },
		{ name: 'zzsl', type: 'float',hidden:true },
		{ name: 'csdj', type: 'float',hidden:true },
		{ name: 'csje', type: 'float',hidden:true },
		{ name: 'zzse', type: 'float',hidden:true },
		{ name: 'wbbh',hidden:true },
		{ name: 'wbhl', type: 'float',hidden:true },
		{ name: 'wbdj', type: 'float',hidden:true },
		{ name: 'wbje', type: 'float',hidden:true },
		{ name: 'dhxs', type: 'float',hidden:true },
		{ name: 'mxzs', type: 'float',hidden:true },
		{ name: 'cpbz',hidden:true },
		{ name: 'chrq', type: 'date', dateFormat: 'Y-m-d H:i:s',hidden:true },
		{ name: 'khxh',hidden:true },
		{ name: 'plmth',hidden:true },
		{ name: 'plmtx',hidden:true }
	]
});
