Ext.define('erp.view.purchaseOrder.model.ProPlanImp', {
	extend: 'Ext.data.Model',
	fields: [
		{ name: 'jhh' ,header:'计划号',columnWidth:80},
		{ name: 'jhlbmc',header:'计划类别',columnWidth:80 },
		{ name: 'czym',header:'操作员',columnWidth:80},
		{ name: 'cpbh',header:'产品编号',columnWidth:80},
		{ name: 'cpmc',header:'产品名称',columnWidth:160},
		{ name: 'khmc',header:'客户名称',columnWidth:160},
		{ name: 'khxh',header:'客户型号',columnWidth:100},
		{ name: 'jhbz',header:'生产单号',columnWidth:100},
		{ name: 'jldw',header:'单位',columnWidth:60},
		{ name: 'jhsl', type: 'float',header:'计划数量-',columnWidth:100},
		{ name: 'cgsl', type: 'float',header:'已转数量=',columnWidth:100},
		{ name: 'wzsl', type: 'float',header:'未转数量',columnWidth:100},
		{ name: 'wcrq', type: 'date',dateFormat: 'Y-m-d H:i:s',header:'完工日期',columnWidth:100},
		{ name: 'ddh',header:'订单号',columnWidth:100},
		{ name: 'zjhh',header:'主计划号',columnWidth:100},
		{ name: 'zcpmc',header:'主产品名称',columnWidth:240},
		{ name: 'sqh',header:'需求号',columnWidth:100},
		{ name: 'psjq', type: 'date', dateFormat: 'Y-m-d H:i:s',header:'评审交期',columnWidth:100},
		{ name: 'pono',header:'PO#',columnWidth:100},
		{ name: 'ywms',header:'英文描述',columnWidth:100},
		{ name: 'jhlb' ,hidden:true},
		{ name: 'jhbh', type: 'int' ,hidden:true},
		{ name: 'jhxh', type: 'int' ,hidden:true},
		{ name: 'sxrq', type: 'date', dateFormat: 'Y-m-d H:i:s' ,hidden:true},
		{ name: 'cptx1' ,hidden:true},
		{ name: 'cptx2' ,hidden:true},
		{ name: 'cptx3' ,hidden:true},
		{ name: 'dhsl', type: 'float' ,hidden:true},
		{ name: 'zwxs', type: 'float' ,hidden:true},
		{ name: 'fdbl', type: 'float' ,hidden:true},
		{ name: 'rksl', type: 'float' ,hidden:true},
		{ name: 'bcps', type: 'float' ,hidden:true},
		{ name: 'scww', type: 'float' ,hidden:true},
		{ name: 'zcpbh' ,hidden:true},
		{ name: 'cpbz' ,hidden:true},
		{ name: 'wcbj', type: 'int' ,hidden:true},
		{ name: 'qfbj', type: 'int' ,hidden:true},
		{ name: 'qfsj', type: 'date', dateFormat: 'Y-m-d H:i:s' ,hidden:true},
		{ name: 'qfrm',hidden:true },
		{ name: 'sdbj', type: 'int',hidden:true },
		{ name: 'sdrm',hidden:true },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s',hidden:true },
		{ name: 'zzbj', type: 'int',hidden:true },
		{ name: 'sqbh', type: 'float',hidden:true },
		{ name: 'sqxh', type: 'float',hidden:true },
		{ name: 'jybj', type: 'int',hidden:true },
		{ name: 'ggcs', type: 'float',hidden:true },
		{ name: 'zybj', type: 'int',hidden:true },
		{ name: 'wxbj', type: 'int',hidden:true },
		{ name: 'jyrm',hidden:true },
		{ name: 'jysj', type: 'date', dateFormat: 'Y-m-d H:i:s',hidden:true },
		{ name: 'qcbj', type: 'int',hidden:true },
		{ name: 'ddbh', type: 'float',hidden:true },
		{ name: 'ddxh', type: 'float' ,hidden:true},
		{ name: 'wxsj', type: 'date', dateFormat: 'Y-m-d H:i:s',hidden:true },
		{ name: 'jsdj', type: 'float' ,hidden:true},
		{ name: 'jsje', type: 'float' ,hidden:true},
		{ name: 'scbj', type: 'int',hidden:true },
		{ name: 'wcxs', type: 'int' ,hidden:true},
		{ name: 'khbh' ,hidden:true},
		{ name: 'zddbh', type: 'float',hidden:true },
		{ name: 'zddxh', type: 'float' ,hidden:true},
		{ name: 'plmth' ,hidden:true},
		{ name: 'plmtx' ,hidden:true},
		{ name: 'clhh' ,hidden:true},
		{ name: 'clmc' ,hidden:true}
	]
});
