Ext.define('erp.view.purchaseOrder.model.PurBom', {
	extend: 'Ext.data.Model',
	idProperty: 'jlxh',
	fields: [
		{ name: 'htbh', type: 'int' },
		{ name: 'htxh', type: 'int' },
		{ name: 'jlxh', type: 'int' },
		{ name: 'cpbh' },
		{ name: 'cptx1' },
		{ name: 'cptx2' },
		{ name: 'cptx3' },
		{ name: 'bbbh' },
		{ name: 'jgbh' },
		{ name: 'mjbz', type: 'int' },
		{ name: 'lbbh' },
		{ name: 'bjbb' },
		{ name: 'clhh' },
		{ name: 'clmc' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'jldw' },
		{ name: 'cllx', type: 'int' },
		{ name: 'djyl', type: 'float' },
		{ name: 'gjdj', type: 'float' },
		{ name: 'wxsh', type: 'float' },
		{ name: 'clje', type: 'float' },
		{ name: 'bzsm' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zzhxs', type: 'float' },
		{ name: 'plmth' },
		{ name: 'plmtx' },
		{ name:'lbmc'},
		{ name:'login_id'},
		{ name:'ip'},
		{ name:'csbh'},
		{ name: 'xdrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name:'csmc'},
		{ name: 'ewje', type: 'float' },
		{ name: 'gjdj_old', type: 'float' },
		{ name: 'gjdj_new', type: 'float' }
	]
});
