Ext.define('erp.view.purchaseOrder.model.PurchaseOrderDetail', {
	extend: 'Ext.data.Model',
	//idProperty: 'htxh',
	fields: [
		{ name: 'htbh', type: 'int' },
		{ name: 'htxh', type: 'int' },
		{ name: 'clhh' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'jldw' },
		{ name: 'cgsl', type: 'float' },
		{ name: 'ycgl', type: 'float' },
		{ name: 'dhrk', type: 'float' },
		{ name: 'cgww', type: 'float' },
		{ name: 'cgwwje', type: 'float' },
		{ name: 'cgdj', type: 'float' },
		{ name: 'wbbh' },
		{ name: 'wbdj', type: 'float' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'cgje', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'zzsl', type: 'float' },
		{ name: 'cgrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'ghzq', type: 'float' },
		{ name: 'jhrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'kzdj', type: 'float' },
		{ name: 'qrjq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'hqjq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'sdck' },
		{ name: 'bzsm' },
		{ name: 'wcbj', type: 'int' },
		{ name: 'zzbj', type: 'int' },
		{ name: 'hsbm' },
		{ name: 'fzsl', type: 'float' },
		{ name: 'fzdw' },
		{ name: 'ysgg' },
		{ name: 'wkjq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gxsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'clmc' },
		{ name: 'clth' },
		{ name: 'zzhxs', type: 'float' },
		{ name: 'cjjhrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'rksl', type: 'float' },
		{ name: 'rkww', type: 'float' },
		{ name: 'jhh' },
		{ name: 'ddh' },
		{ name: 'cgh' },
		{ name: 'djsl', type: 'float' },
		{ name: 'drsl', type: 'float' },
		{ name: 'dtsl', type: 'float' },
		{ name: 'sqh' },
		{ name: 'sgh' },
		{ name: 'zxhth' },
		{ name: 'zxhtbh', type: 'int' },
		{ name: 'zxhtxh', type: 'int' },
		{ name: 'sqbh', type: 'int' },
		{ name: 'sqxh', type: 'int' },
		{ name: 'jhbh', type: 'int' },
		{ name: 'jhxh', type: 'int' },
		{ name: 'htbz' },
		{ name: 'kjlx', type: 'int' },
		{ name: 'cjsl', type: 'float' },
		{ name: 'lgxs', type: 'float' },
		{ name: 'khbh' },
		{ name: 'cpbh' },
		{ name: 'pxxh', type: 'int' },
		{ name: 'wxbj', type: 'int' },
		{ name: 'gzbj', type: 'int' },
		{ name: 'dlgs', type: 'float' },
		{ name: 'zzrm' },
		{ name: 'zzsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'ggcs', type: 'float' },
		{ name: 'zzlx' },
		{ name: 'zzyx' },
		{ name: 'scbj', type: 'int' },
		{ name: 'mjh' },
		{ name: 'pzqrbj', type: 'int' },
		{ name: 'cfh' },
		{ name: 'plmth' },
		{ name: 'plmtx' },
		{ name: 'plmth_cp' },
		{ name: 'plmtx_cp' },
		{ name:'khjc'},
		{ name:'cpmc'},
		{ name:'hsbmmc'},
		{ name:'wbdh'},
		{ name:'zzlxmc'},
		{ name:'sdckmc'},
		{ name:'xjqrbj', type: 'int' },
		{ name:'ddbh', type: 'int' },
		{ name:'ddxh', type: 'int' },
		{ name:'clbz'},
		{ name:'bzxx'},
		{ name:'cpxj'},
		{ name: 'csxs1', type: 'float' },
		{ name: 'csxs2', type: 'float' },
		{ name: 'csxs3', type: 'float' },
		{ name: 'csxs4', type: 'float' },
		{ name: 'csxs5', type: 'float' },
		{ name: 'csxs6', type: 'float' },
		{ name: 'csxs7', type: 'float' },
		{ name: 'csxs8', type: 'float' },
		{ name:'jhlb'},
		{ name:'cgbh'},
		{ name:'cgxh', type: 'int' },
		{ name:'sgbh'},
		{ name:'sgxh', type: 'int' },
		{ name:'xzbj', type: 'int' },
		{ name:'fzkj', type: 'float' },
		{ name:'fzzbj', type: 'float' },
		{ name:'csjg', type: 'float' },
		{ name:'dgyl'},
		{ name:'mxzs', type: 'float' },
		{ name:'pzqrrm'},
		{ name:'pzqrsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name:'psjq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name:'cfbj', type: 'int' },
		{ name:'cfbh', type: 'int' },
		{ name:'cfxh', type: 'int' },
		{ name:'fach'},
		{ name:'khxh'},
		{ name:'ywms'},
		{ name:'pono'},
		{ name:'xmsjbc'},
		{ name:'login_id'},
		{ name:'ip'},
		{ name:'htzzlxmc'},
		{ name:'zldj', type: 'float' ,hidden:true},
		{ name:'requestid' ,hidden:true}
	]
});
