Ext.define('erp.view.purchaseOrder.model.PurPanelImp', {
	extend: 'Ext.data.Model',
	//idProperty: 'cgbh',
	fields: [
		{ name: 'spbj', type: 'int' ,header:'分配',columnWidth:50,isSign:true,allow_summaryOne:true},
		{ name: 'wxbj', type: 'int' ,header:'外箱',columnWidth:40,isSign:true,allow_summaryOne:true},
		{ name: 'lbmc',header:'计划类别',columnWidth:80},
		{ name: 'cgh' ,header:'采计号',columnWidth:80},
		{ name: 'ddh' ,header:'订单号',columnWidth:70},
		{ name: 'sqh' ,header:'申请号',columnWidth:70},
		{ name: 'hyhm',header:'生产单号',columnWidth:100 },
		{ name: 'cgzm',header:'采购组' ,columnWidth:70},
		{ name: 'cgyxm' ,header:'采购员',columnWidth:70},
		{ name: 'clhh',header:'材料货号' ,columnWidth:80},
		{ name: 'khjc',header:'客户简称' ,columnWidth:120},
		{ name: 'cpmc',header:'产品名称' ,columnWidth:160 },
		{ name: 'clmc',header:'材料名称' ,columnWidth:240 },
		{ name: 'cltx1',header:'规格尺寸' ,columnWidth:80 },
		{ name: 'jldw',header:'计量单位' ,columnWidth:40 },
		{ name: 'cgsl', type: 'float',header:'计划数量',columnWidth:80,allow_summary:true,summaryFomat:'0,000.000'},
		{ name: 'htsl', type: 'float',header:'-已转数量',columnWidth:80,allow_summary:true,summaryFomat:'0,000.000'},
		{ name: 'wzsl', type: 'float',header:'=未转数量',columnWidth:80,allow_summary:true,summaryFomat:'0,000.000'},
		{ name: 'fzdw',header:'辅助单位' ,columnWidth:40  },
		{ name: 'fzsl', type: 'float',header:'辅助数量',columnWidth:80,allow_summary:true,summaryFomat:'0,000.000'},
		{ name: 'fzwz', type: 'float',header:'辅助未转',columnWidth:80,allow_summary:true,summaryFomat:'0,000.000'},
		{ name: 'dlgs', type: 'float',header:'短料根数',columnWidth:80,allow_summary:true,summaryFomat:'0,000.000'},
		{ name: 'yzdl', type: 'float',header:'-已转短料',columnWidth:80,allow_summary:true,summaryFomat:'0,000.000'},
		{ name: 'wzdl', type: 'float',header:'-未转短料',columnWidth:80,allow_summary:true,summaryFomat:'0,000.000' },
		{ name: 'cgrq', type: 'date', dateFormat: 'Y-m-d H:i:s',header:'采购日期',columnWidth:85},
		{ name: 'jhrq', type: 'date', dateFormat: 'Y-m-d H:i:s',header:'交货日期',columnWidth:85},
		{ name: 'wkjq', type: 'date', dateFormat: 'Y-m-d H:i:s',header:'物控交期',columnWidth:85},
		{name:'ckmc',header:'送达仓库',columnWidth:80},
		{name:'csmc',header:'供应厂商',columnWidth:160},
		{ name: 'bzsm',header:'备注说明',columnWidth:160},
		{ name: 'cgbh', type: 'int',hidden:true},
		{ name: 'cgxh', type: 'int' ,hidden:true},
		{ name: 'csbh' ,hidden:true},
		{ name: 'cgym' ,hidden:true},
		{ name: 'ghzq', type: 'float' ,hidden:true},
		{ name: 'sdck' ,hidden:true},
		{ name: 'jhbh', type: 'int',hidden:true },
		{ name: 'jhxh', type: 'int',hidden:true },
		{ name: 'cgdj', type: 'float',hidden:true },
		{ name: 'kzdj', type: 'float',hidden:true },
		{ name: 'cltx2',hidden:true },
		{ name: 'cltx3',hidden:true },
		{ name: 'ysgg',hidden:true },
		{ name: 'jhlb',hidden:true },
		{ name: 'lbbh',hidden:true },
		{ name: 'clth',hidden:true },
		{ name: 'fzzbj', type: 'int',hidden:true },
		{ name: 'cgzh' ,hidden:true},
		{ name: 'txgz' ,hidden:true},
		{ name: 'hsbm' ,hidden:true},
		{ name: 'jhbz' ,hidden:true},
		{ name: 'ddbh', type: 'int' ,hidden:true},
		{ name: 'ddxh', type: 'int' ,hidden:true},
		{ name: 'khbh' ,hidden:true},
		{ name: 'cpbh' ,hidden:true},
		{ name: 'sqxh', type: 'int' ,hidden:true},
		{ name: 'sqbh', type: 'int' ,hidden:true}
	]
});
