Ext.define('erp.master.vendorFiles.model.VendorFiles', {
	extend: 'Ext.data.Model',
	idProperty: 'csbh',
	fields: [
		{ name: 'csbh' },
		{ name: 'csjc' },
		{ name: 'csmc' },
		{ name: 'yhbh' },
		{ name: 'cglb' },
		{ name: 'hzcs' },
		{ name: 'psbj', type: 'int' },
		{ name: 'fzrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'fkts', type: 'float' },
		{ name: 'khbh' },
		{ name: 'cslb' },
		{ name: 'wbbh' },
		{ name: 'xyed', type: 'float' },
		{ name: 'csdh' },
		{ name: 'cscz' },
		{ name: 'lxrm' },
		{ name: 'csdz' },
		{ name: 'csyb' },
		{ name: 'cssh' },
		{ name: 'cszh' },
		{ name: 'bzsm' },
		{ name: 'gdbj', type: 'int' },
		{ name: 'czrm' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'spbj', type: 'int' },
		{ name: 'sprm' },
		{ name: 'spsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'cslx' },
		{ name: 'ywmc' },
		{ name: 'zgrd' },
		{ name: 'tdrd' },
		{ name: 'hdxz' },
		{ name: 'fktj' },
		{ name: 'scbj', type: 'int' },
		{ name: 'kpbj', type: 'int' },
		{ name: 'kpdj' },
		{ name: 'khyh' },
		{ name: 'xdbl', type: 'float' },
		{ name: 'jybj', type: 'int' },
		{ name: 'hddw' },
		{ name: 'ztdw' },
		{ name: 'wbmc'},
		{ name: 'wbdh'}
	]
});
