Ext.define('erp.arrivalRegister.model.ContractImp', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
	{ name : 'htbh',type: 'int'},
	{ name : 'htxh',type: 'int'},
	{ name : 'cgbh',type: 'int'},
	{ name : 'cgxh',type: 'int'},
	{ name : 'jhbh',type: 'int'},
	{ name : 'jhxh',type: 'int'},
	{ name : 'zjbj',type: 'int'},
	{ name : 'fzzbj',type: 'int'},
	{ name : 'khxh'},
	{ name : 'zjbh',type: 'int'},
	{ name : 'zjxh',type: 'int'},
	{ name : 'csbh'},
	{ name : 'clhh'},
	{ name : 'cltx1'},
	{ name : 'cltx2'},
	{ name : 'cltx3'},
	{ name : 'jldw'},
	{ name : 'csmc'},
	{ name : 'jhh'},
	{ name : 'hth'},
	{ name : 'bzsm'},
	{ name : 'fzdw'},
	{ name : 'clmc'},
	{ name : 'hsbm'},
	{ name : 'cpmc'},
	{ name : 'zcpmc'},
	{ name : 'jhbz'},
	{ name : 'plmtx'},
	{ name : 'plmth'},
	{ name : 'zjhh'},
	{ name : 'cgsl',type:'float'},
	{ name : 'ycgl',type:'float'},
	{ name : 'dhrk',type:'float'},
	{ name : 'wdsl',type:'float'},
	{ name : 'cgdj',type:'float'},
	{ name : 'fzsl',type:'float'},
	{ name : 'wkjq', type: 'date', dateFormat: 'Y-m-d H:i:s'},
	{ name : 'sxrq', type: 'date', dateFormat: 'Y-m-d H:i:s'}
	]

})