Ext.define('erp.arrivalRegister.model.OutSideImp', {
	extend: 'Ext.data.Model',
	idProperty: '',
    fields: [
    {name : 'wxh'},
    {name : 'jhh'},
    {name : 'cpbh'},
    {name : 'jldw'},
    {name : 'clhh'},
    {name : 'cltx1'},
    {name : 'cltx2'},
    {name : 'cltx3'},
    {name : 'fzdw'},
    {name : 'csbh'},
    {name : 'bzsm'},
    {name : 'clmc'},
    {name : 'hsbm'},
    {name : 'cpmc'},
    {name : 'zcpmc'},
    {name : 'plmtx'},
    {name : 'plmth'},
    {name : 'wxrq', type: 'date', dateFormat: 'Y-m-d H:i:s'},
    {name : 'wcrq', type: 'date', dateFormat: 'Y-m-d H:i:s'},
    {name : 'wxdh',type: 'int'},
    {name : 'wxxh',type: 'int'},
    {name : 'jhbh',type: 'int'},
    {name : 'jhxh',type: 'int'},
    {name : 'zjbj',type: 'int'},
    {name : 'jhbh',type: 'int'},
    {name : 'jhxh',type: 'int'},
    {name : 'jhbz'},
    {name : 'csmc'},
    {name : 'tcsl',type: 'float'},
    {name : 'jsbl',type: 'float'},
    {name : 'jgsl',type: 'float'},
    {name : 'jgdj',type: 'float'},
    {name : 'dhrk',type: 'float'},
    {name : 'wdsl',type: 'float'},
    {name : 'fzsl',type: 'float'}
    ]
})