Ext.define('erp.PurchaseClearing.model.CostBills', {
	extend: 'Ext.data.Model',
	idProperty: 'rkh',
	fields: [
	  {name : 'ckbh'},
	  {name : 'csbh'},
	  {name : 'clhh'},
	  {name : 'cltx1'},
	  {name : 'cltx2'},
	  {name : 'cltx3'},
	  {name : 'jldw'},
	  {name : 'wbbh'},
	  {name : 'czym'},
	  {name : 'bzsm'},
	  {name : 'clmc'},
	  {name : 'sjly'},
	  {name : 'fzdw'},
	  {name : 'shdh'},
	  {name : 'fplb'},
	  {name : 'fphm'},
	  {name : 'fyxz'},
	  {name : 'cybh'},
	  {name : 'plmth'},
	  {name : 'ckmc'},
	  {name : 'wbmc'},
	  {name : 'yhbh'},
	  {name : 'cglb'},
	  {name : 'hth'},
	  {name : 'sdrm'},
	  {name : 'rklb'},
	  {name : 'rklbmc'},
	  {name:'rkh',convert:function(v,rec){
	  	return rec.get('rkdh')+'-'+rec.get('rkxh')
	  }},
	  {name : 'rkdh',type: 'int'},
	  {name : 'rkxh',type: 'int'},
	  {name : 'tzdh',type: 'int'},
	  {name : 'glht',type: 'int'},
	  {name : 'cgbh',type: 'int'},
	  {name : 'cgxh',type: 'int'},
	  {name : 'htbh',type: 'int'},
	  {name : 'htxh',type: 'int'},
	  {name : 'cgsl',type: 'float'},
	  {name : 'dhsl',type: 'float'},
	  {name : 'rksl',type: 'float'},
	  {name : 'bj',type: 'int'},
	  {name : 'hcdh',type: 'int'},
	  {name : 'hcxh',type: 'int'},
	  {name : 'tjbj',type: 'int'},
	  {name : 'hxbj',type: 'int'},
	  {name : 'hzbj',type: 'int'},
	  {name : 'rkdj',type: 'float'},
	  {name : 'rkje',type: 'float'},
	  {name : 'wbhl',type: 'float'},
	  {name : 'wbdj',type: 'float'},
	  {name : 'wbje',type: 'float'},
	  {name : 'fzsl',type: 'float'},
	  {name : 'zzsl',type: 'float'},
	  {name : 'jgje',type: 'float'},
	  {name : 'jgdj',type: 'float'},
	  {name : 'zzse',type: 'float'},
	  {name : 'csdj',type: 'float'},
	  {name : 'csje',type: 'float'},
	  {name : 'wjdj',type: 'float'},
	  {name : 'wjje',type: 'float'},
	  {name : 'gcdj',type: 'float'},
	  {name : 'gcje',type: 'float'},
	  {name : 'rkrq',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	/*  {name : 'fyrq',type: 'date', dateFormat: 'Y-m-d H:i:s'},*/
	  {name : 'czsj',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name : 'dhrq',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name : 'shsj',type: 'date', dateFormat: 'Y-m-d H:i:s'}/*,
	  {name : 'sdsj',type: 'date', dateFormat: 'Y-m-d H:i:s'}*/
	]
});
