Ext.define('erp.supplyInvoice.model.SupplyInvoice', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'fplx'},
		{ name: 'fplb'},
		{ name: 'fphm'},
		{ name: 'kprq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'csbh'},
		{ name: 'csmc'},
		{ name: 'yfbj', type: 'int'  },
		{ name: 'shbj', type: 'float' },
		{ name: 'shrm'},
		{ name: 'shsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jzrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'fpsl', type: 'float' },
		{ name: 'fpje', type: 'float' },
		{ name: 'csje', type: 'float' },
		{ name: 'zzse', type: 'float' },
		{ name: 'bzsm'},
		{ name: 'kprm'},
		{ name: 'kpsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'pzbj', type: 'int'  },
		{ name: 'pzbh', type: 'float' },
		{ name: 'ztbh'},
		{ name: 'dfdm'},
		{ name: 'kmdm'},
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'pzh' },
		{ name: 'ztdw'},
		{ name: 'djbj', type: 'int'  },
		{ name: 'djrm'},
		{ name: 'djsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'fptt'},
		{ name: 'yhbh'},
		{ name: 'cglb'},
		{ name: 'wbbh'},
		{ name: 'sqje' , type: 'float' },
		{ name: 'yfkje', type: 'float' },
		{ name: 'wqje' , type: 'float' },
		{ name: 'zyje' , type: 'float' },
		{ name: 'wbsq' , type: 'float' },
		{ name: 'wbyfk', type: 'float' },
		{ name: 'wqwb' , type: 'float' },
		{ name: 'cgym'},
		{ name: 'ttzh'},
		{ name: 'dsbj', type: 'int'  },
		{ name: 'dsrm'},
		{ name: 'dssj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zfph'},
		{ name: 'jyid'},
		{ name: 'ycbj', type: 'int' },
		{ name: 'hcxx'},
		{ name: 'yjfkrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'wjje', type: 'float' },
		{ name: 'ycje', type: 'float' },
		{ name: 'xcje', type: 'float' },
		{ name: 'dcbj', type: 'int' }
	]
});
