Ext.define('erp.PurchaseClearing.model.Cost', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
	  {name : 'yhbh'},
	  {name : 'cglb'},
	  {name : 'csbh'},
	  {name : 'fyzy'},
	  {name : 'fylb'},
	  {name : 'bzsm'},
	  {name : 'jhh'},
	  {name : 'sdrm'},
	  {name : 'ftlp'},
	  {name : 'fphm'},
	  {name : 'czym'},
	  {name : 'csmc'},
	  {name : 'cybh'},
	  {name : 'wbbh'},
	  {name : 'hsbm'},
	  {name : 'bmmc'},
	  {name : 'fyxz'},
	  {name : 'wbdh'},
	  {name : 'ftms'},
	  {name : 'fsbm'},
	  {name : 'zzsl'},
	  {name : 'htbh'},
	  {name : 'htxh'},
	  {name : 'hth'},
	  {name : 'hxbj',type: 'int'},
	  {name : 'sdbj',type: 'int'},
	  {name : 'fydh',type: 'float'},
	  {name : 'fyxh',type: 'float'},
	  {name : 'fysl',type: 'float'},
	  {name : 'fydj',type: 'float'},
	  {name : 'fyje',type: 'float'},
	  {name : 'jhbh',type: 'float'},
	  {name : 'jhxh',type: 'float'},
	  {name : 'tzdh',type: 'float'},
	  {name : 'wbhl',type: 'float'},
	  {name : 'wbje',type: 'float'},
	  {name : 'wbdj',type: 'float'},
	  {name : 'ftxs',type: 'float'},
	  {name : 'csdj',type: 'float'},
	  {name : 'csje',type: 'float'},
	  {name : 'zzse',type: 'float'},
	  {name : 'fyrq',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name : 'sdsj',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	  {name : 'czsj',type: 'date', dateFormat: 'Y-m-d H:i:s'}
	]
});
