Ext.define('erp.PurchaseClearing.model.JsFydbImp', {
	extend: 'Ext.data.Model',
	idProperty: 'fyh',
	fields: [
	 {name : 'fydh',type: 'float'},
	 {name : 'fyxh',type: 'float'},
	 {name : 'fysl',type: 'float'},
	 {name : 'fydj_hx',type: 'float'},
	 {name : 'fyje_hx',type: 'float'},
	 {name : 'csdj_hx',type: 'float'},
	 {name : 'csje_hx',type: 'float'},
	 {name : 'zzse_hx',type: 'float'},
	 {name : 'wbhl_hx',type: 'float'},
	 {name : 'wbdj_hx',type: 'float'},
	 {name : 'wbje_hx',type: 'float'},
	 {name : 'wxdh',type: 'float'},
	 {name : 'fydj',type: 'float'},
	 {name : 'fyje',type: 'float'},
	 {name : 'csdj',type: 'float'},
	 {name : 'csje',type: 'float'},
	 {name : 'htbh',type: 'float'},
	 {name : 'wbhl',type: 'float'},
	 {name : 'wbje',type: 'float'},
	 {name : 'wbdj',type: 'float'},
	 {name : 'tzdh',type: 'float'},
	 {name : 'ftxs',type: 'float'},
	 {name : 'jhbh',type: 'int'},
	 {name : 'jhxh',type: 'int'},
	 {name : 'htxh',type: 'int'},
	 {name : 'spbj',type: 'int'},
	 {name : 'jzzt',type: 'int'},
	 {name : 'xzbj',type: 'int'},
	 {name : 'scbj',type: 'int'},
	 {name : 'dybj',type: 'int'},
	 {name : 'hxbj',type: 'int'},
	 {name : 'sdbj',type: 'int'},
	 {name : 'tjbj',type: 'int'},
	 {name : 'cfxh',type: 'int'},
	 {name : 'wxxh',type: 'int'},
	 {name : 'yhbh'},
	 {name : 'cglb'},
	 {name : 'csbh'},
	 {name : 'fyzy'},
	 {name : 'zzsl_hx'},
	 {name : 'zzsl'},
	 {name : 'jhh'},
	 {name : 'hth'},
	 {name : 'bzsm'},
	 {name : 'csmc'},
	 {name : 'fplb'},
	 {name : 'fphm'},
	 {name : 'sdrm'},
	 {name : 'tjrm'},
	 {name : 'fzhm'},
	 {name : 'czym'},
	 {name : 'cybh'},
	 {name : 'fylx'},
	 {name : 'wbbh'},
	 {name : 'wbdh'},
	 {name : 'hsbm'},
	 {name : 'fyxz'},
	 {name : 'ftms'},
	 {name : 'cslb'},
	 {name : 'gxbh'},
	 {name : 'fsbm'},
	 {name : 'bmmc'},
	 {name : 'csmc'},
	 {name : 'sdsj',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	 {name : 'tjsj',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	 {name : 'czsj',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	 {name : 'dysj',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	 {name : 'hxrq',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	 {name : 'fyrq',type: 'date', dateFormat: 'Y-m-d H:i:s'},
	 {name:'fyh',convert:function(v,rec){
	  	return rec.get('fydh')+'-'+rec.get('fyxh')
	  }}
	]
});
