Ext.define('erp.PurchaseClearing.model.JsRkdbImp', {
	extend: 'Ext.data.Model',
	idProperty: 'rkh',
	fields: [
	          {header: '锁定',name: 'sdbj',type: 'int' ,columnWidth:38,isSign:true,summaryRenderer : function(value, summaryData,dataIndex) {
				return '合计';
			    },allow_summaryOne:true
		        },
		     	{header:  '赠送',name: 'zsbj',type: 'int' ,columnWidth:38,isSign:true},
		     	{header: '核销',name:'hxbj',type: 'int' ,columnWidth:38,isSign:true,hidden : true
		     	},
		     	{header:  '估价',name: 'gjbj',type: 'int' ,columnWidth:38,isSign:true},
		        {header : '仓库名称',columnWidth : 80,name: 'ckmc'},
		        {header : '送货日期',type: 'date',columnWidth: 80,name: 'shsj',dateFormat: 'Y.m.d H:i:s'},
		     	{header : '送货单号',columnWidth: 80,name: 'shdh' },
		     	{header : '入库日期',type: 'date',columnWidth: 80,name: 'rkrq',dateFormat: 'Y.m.d H:i:s'},
		     	{header : '入库单号',type : 'int',columnWidth: 70,name: 'rkdh' },
		     	{header : '序号',type : 'int',columnWidth: 50,name: 'rkxh' },
		     	{header : '材料货号',type : 'int',columnWidth: 70,name: 'clhh' },
		     	{header : '材料名称',columnWidth: 250,name: 'clmc' },
		     	{header : '入库数量',type: 'float',columnWidth: 100,name: 'rksl',
		                          summaryType: 'sum',
		                          summaryRenderer: Ext.util.Format.floatRenderer,
		                          renderer:Ext.util.Format.floatRenderer},
		        {header : '含税单价',type: 'float',columnWidth : 80,name: 'rkdj_hx'},
				{header : '含税金额',type: 'float',columnWidth : 100,name: 'rkje_hx',
		                          summaryType: 'sum',
		                          summaryRenderer: Ext.util.Format.floatRenderer,
					              renderer:function(value, summaryData, name) {
					              	 return Ext.util.Format.number(value,'0,000.00') ;
					            }},
		     	{header : '合同编号',type : 'int',columnWidth: 80,name: 'htbh' },
		     	{header : '厂商编号',columnWidth: 80,name: 'csbh',hidden : true },
		     	{header : '合同序号',type : 'int',columnWidth: 80,name: 'htxh' },
		     	{header : '采购号',columnWidth: 70,name: 'cgh' },
		     	{header : '关联合同编号',type : 'int',columnWidth: 80,name: 'glht' ,
				 renderer:function(v){if(v==0){return ' '}else{return v}}},
		     	
		     	{header : '规格尺寸',columnWidth: 120,name: 'cltx1' },
		     	{header : '备注说明',columnWidth: 210,name: 'bzsm' },
		     	{header : '单位',columnWidth: 50,name: 'jldw' },
		     	
		     	{header : '仓库编号',columnWidth : 80,name: 'ckbh',hidden : true},
		     	{header : '加工单价',type: 'float' ,columnWidth: 80,name: 'jgje' ,
				 renderer:function(v){if(v==0){return ' '}else{return v}}},
		     	{header : '加工金额',type: 'float' ,columnWidth: 80,name: 'wxjgje' ,
				 renderer:function(v){if(v==0.00){return ' '}else{return v}},
		                          summaryType: 'sum',
		                          summaryRenderer: Ext.util.Format.floatRenderer,
					              renderer:function(value, summaryData, name) {
					              	 return value!=0? Ext.util.Format.number(value,'0,000.00'):'' ;
					            }},
		     	{header : '操作员',columnWidth: 70,name: 'czym' },
		     	{header : '操作时间',type: 'date',columnWidth: 80,name: 'czsj' ,format:'Y.m.d H:i:s'},
		     	{header : '入库类别',columnWidth : 80,name: 'rklbmc'},
		     	{header : '红冲',type: 'int' ,columnWidth: 50,name:'hcbj',
				 renderer:function(v){if(v==0){return ' '}else{return v}}},
		     	{header : '分组号码',columnWidth: 50,name:'fzhm'},
		     	{header : '外协号',columnWidth : 70,name: 'wxh'},
		     	/*{header : '生产单号',columnWidth :70,name: 'htbz'},*/
		     	{header : '产品编号',columnWidth :70,name: 'cpbh'},
		     	{header : '事物特性',columnWidth :100,name: 'plmth_cp'},
		     	{header : '产品名称',columnWidth :170,name: 'cpmc'},
		     	{header : '税率',type: 'float',columnWidth :70,name: 'zzsl_hx',field:{
			   	  	  			xtype:'numberfield',
			   	  	  			maxValue:1,
			   	  	  			decimalPrecision:2},
			   	  	  		 renderer : Ext.util.Format.percentRenderer},
		     	{header : '除税单价',type: 'float' ,columnWidth :80,name: 'csdj_hx'},
		     	{header : '除税金额',type: 'float' ,columnWidth :100,name: 'csje_hx',
		                          summaryType: 'sum',
		                          summaryRenderer: Ext.util.Format.floatRenderer,
					              renderer:function(value, summaryData, name) {
					              	 return Ext.util.Format.number(value,'0,000.00') ;
					            }},
		     	{header : '税额',type: 'float' ,columnWidth :80,name: 'zzse_hx',
		                          summaryType: 'sum',
		                          summaryRenderer: Ext.util.Format.floatRenderer,
					              renderer:function(value, summaryData, name) {
					              	 return Ext.util.Format.number(value,'0,000.00') ;
					            }},
		     	{header : '币种',columnWidth :70,name: 'wbdh'},
		     	{header : '汇率',type: 'float' ,columnWidth :70,name: 'wbhl_hx',field:{}},
		     	{header : '外币单价',type: 'float' ,columnWidth :100,name: 'wbdj_hx',
				 renderer:function(v){if(v==0){return ' '}else{return v}}},
		     	{header : '外币金额',type: 'float' ,columnWidth :100,name: 'wbje_hx',
				 renderer:function(v){if(v==0.00){return ' '}else{return v}},
		                          summaryType: 'sum',
		                          summaryRenderer: Ext.util.Format.floatRenderer,
					              renderer:function(value, summaryData, name) {
					              	 return Ext.util.Format.number(value,'0,000.00') ;
					            }},
		     	{header : '辅助单位',columnWidth :70,name: 'fzdw'},
		     	{header : '辅助数量',type: 'float',columnWidth :100,name: 'fzsl',
				 renderer:function(v){if(v==0){return ' '}else{return v}},
		                          summaryType: 'sum',
		                          summaryRenderer: Ext.util.Format.floatRenderer,
					              renderer:function(value, summaryData, name) {
					              	 return value;
					            }},
		     	{header : '辅助单价',type: 'float' ,columnWidth :80,name: 'fzdj',
				 renderer:function(v){if(v==0){return ' '}else{return v}}},
		     	{header : '采购类别',columnWidth :70,name: 'cglbmc'},
		     	{header : 'PONO',columnWidth : 80,name:'sxdy09'},
		     	{header : '供应厂商',columnWidth : 220,name:'csmc'},
		     	{header : '采购员',columnWidth : 70,name:'cgyxm'},
		     	{header : '被拆序号',type:'int',columnWidth :70,name:'cfxh',
				 renderer:function(v){if(v==0){return ' '}else{return v}}},
		     	{header : '开票通知号',type : 'int',columnWidth :70,name:'tzdh',
				 renderer:function(v){if(v==0){return ' '}else{return v}}},
		     	{header : '到货日期',type: 'date',columnWidth: 80,name: 'dhrq',dateFormat: 'Y.m.d H:i:s',hidden:true}
		     	,{name : 'wbbh',hidden:true},
	  {name : 'sdrm',hidden:true},
	  {name : 'rklb',hidden:true},
	  {name : 'jkrm',hidden:true},
	  {name : 'cltx2',hidden:true},
	  {name : 'cltx3',hidden:true},
	  {name : 'hwbh',hidden:true},
	  {name : 'pcbh',hidden:true},
	  {name : 'ghpc',hidden:true},
	  {name : 'yhbh',hidden:true},
	  {name : 'sjly',hidden:true},
	  {name : 'hxrm',hidden:true},
	  {name : 'cgym',hidden:true},
	  {name : 'fyxz',hidden:true},
	  {name : 'cybh',hidden:true},
	  {name : 'plmth',hidden:true},
	  {name : 'plmtx',hidden:true},
	  {name : 'plmtx_cp',hidden:true},
	  {name : 'fplb',hidden:true},
	  {name : 'fphm',hidden:true},
	  {name: 'hxrq',type: 'date', dateFormat: 'Y-m-d H:i:s',hidden:true},
	  {name: 'hxsj',type: 'date', dateFormat: 'Y-m-d H:i:s',hidden:true},
	  {name: 'sdsj',type: 'date', dateFormat: 'Y-m-d H:i:s',hidden:true},
	  {name: 'dysj',type: 'date', dateFormat: 'Y-m-d H:i:s',hidden:true},
	  {name: 'zzrq',type: 'date', dateFormat: 'Y-m-d H:i:s',hidden:true},
	  {name: 'pjrq',type: 'date', dateFormat: 'Y-m-d H:i:s',hidden:true},
	  {name : 'tjbj',type : 'int',hidden:true},
	  {name : 'wxdh',type : 'int',hidden:true},
	  {name : 'wxxh',type : 'int',hidden:true},
	  {name : 'hzbj',type : 'int',hidden:true},
	  {name : 'zzsl',type : 'float',hidden:true},
	  {name : 'tjdh',type : 'int',hidden:true},
	  {name : 'cgsl',type : 'float',hidden:true},
	  {name : 'cgbh',type : 'int',hidden:true},
	  {name : 'cgxh',type : 'int',hidden:true},
	  {name : 'hcdh',type : 'int',hidden:true},
	  {name : 'hcxh',type : 'int',hidden:true},
	  {name : 'wgbj',type : 'int',hidden:true},
	  {name : 'jzzt',type : 'int',hidden:true},
	  {name : 'cglb',hidden:true},
	  {name : 'xzbj',type : 'int',hidden:true},
	  {name : 'scbj',type : 'int',hidden:true},
	  {name : 'rkdj',type: 'float',hidden:true},
	  {name : 'rkje',type: 'float',hidden:true},
	  {name : 'csdj',type: 'float',hidden:true},
	  {name : 'csje',type: 'float',hidden:true},
	  {name : 'jhbh',type: 'float',hidden:true},
	  {name : 'jhxh',type: 'float',hidden:true},
	  {name : 'dhdh',type: 'float',hidden:true},
	  {name : 'dhxh',type: 'float',hidden:true},
	  {name : 'clje',type: 'float',hidden:true},
	  {name : 'wbdj',type: 'float',hidden:true},
	  {name : 'wbje',type: 'float',hidden:true},
	  {name : 'hth',hidden:true},
	  {name:'rkh',convert:function(v,rec){
	  	return rec.get('rkdh')+'-'+rec.get('rkxh')
	  }}]
});
