Ext.define('erp.supplyInvoice.model.InventoryList', {
	extend: 'Ext.data.Model',
	idProperty: 'fplb'+'fphm',
	fields: [
		{ name: 'djlx'},
		{ name: 'ckbh'},
		{ name: 'rkdh', type: 'float' },
		{ name: 'rkxh', type: 'float' },
		{ name: 'rkrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'clhh'},
		{ name: 'cltx1'},
		{ name: 'cltx2'},
		{ name: 'cltx3'},
		{ name: 'jldw'},
		{ name: 'rksl', type: 'float' },
		{ name: 'rkdj', type: 'float' },
		{ name: 'rkje', type: 'float' },
		{ name: 'zzsl', type: 'float' },
		{ name: 'csdj', type: 'float' },
		{ name: 'csje', type: 'float' },
		{ name: 'zzse', type: 'float' },
		{ name: 'wbbh'},
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbdj', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'rklb'},
		{ name: 'hxbj' ,type: 'int'  },
		{ name: 'hcbj' ,type: 'int'  },
		{ name: 'clmc'},
		{ name: 'fzdw'},
		{ name: 'fzsl', type: 'float' },
		{ name: 'hth'},
		{ name: 'wxh'},
		{ name: 'cybh'},
		{ name: 'cgyxm'},
		{ name: 'shdh'},
		{ name: 'shsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'mxzl'},
		{ name: 'fyxz'},
		{ name: 'bzsm'},
		{ name: 'khbh'},
		{ name: 'plmth'},
		{ name: 'plmlx'}
	]
});