Ext.define('erp.supplyInvoice.model.PayDetail', {
	extend: 'Ext.data.Model',
	idProperty: 'fplb'+'fphm',
	fields: [
		{ name: 'zdsx', type: 'float' },
		{ name: 'zfpzh'},
		{ name: 'zfrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zfje', type: 'float' },
		{ name: 'zfxs'},
		{ name: 'zhbh'},
		{ name: 'csbh'},
		{ name: 'bzsm'},
		{ name: 'czym'},
		{ name: 'sdbj', type: 'int'  },
		{ name: 'wbbh'},
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'kmdm'},
		{ name: 'dfdm'},
		{ name: 'htbh', type: 'float' },
		{ name: 'lbbh'},
		{ name: 'xjlb'},
		{ name: 'hslb'},
		{ name: 'qtlb'},
		{ name: 'qtfx', type: 'int'  },
		{ name: 'pzbj', type: 'int'  },
		{ name: 'ztbh'},
		{ name: 'pzlb'},
		{ name: 'pzbh', type: 'float' },
		{ name: 'jdfx', type: 'float' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czym'},
		{ name: 'sdrm'},
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'yhbh'},
		{ name: 'cglb'},
		{ name: 'csmc'},
		{ name: 'fplb'},
		{ name: 'fphm'},
		{ name: 'syjhbh', type: 'float' },
		{ name: 'syjhxh' , type: 'float' },
		{ name: 'syh'},
		{ name: 'fkjhbh', type: 'float' },
		{ name: 'fkjhxh' , type: 'float' },
		{ name: 'fkh'}
	]
});