Ext.define('erp.purchaseInspectionManage.model.EditPurchaseInspection', {
	extend: 'Ext.data.Model',
	idProperty: 'yhno,yhxh',
	fields: [
		{ name: 'yhno', type: 'int' },
		{ name: 'yhxh', type: 'int' },
		{name: 'yhh' },	
		{name: 'yhcs', type: 'int' },
		{name: 'yhjl' },
		{name: 'hth' },
		{name: 'ddh' },
		{name: 'pono' },
		{name: 'khxh' },
		{name: 'khmc' },
		{name: 'cpbh' },
		{name: 'cpmc' },
		{name: 'jldw' },
		{name: 'tzsl' ,type: 'float'},
		{name: 'cgsl' ,type: 'float'},
		{name: 'scdh' },
		{name: 'wxh' },
		{name: 'cfh' },
		{name: 'xgg' },
		{name: 'xc' ,type: 'float'},
		{name: 'xk' ,type: 'float'},
		{name: 'xg' ,type: 'float'},
		{name: 'xtj' ,type: 'float'},
		{name: 'xzs' ,type: 'float'},
		{name: 'xmz' ,type: 'float'},
		{name: 'xjz' ,type: 'float'},
		{name: 'gysmc' },
		{name: 'ywy' },
		{name: 'bzzl' },
		{name: 'yhrq', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{name: 'yhdd' },
		{name: 'chdd' },		
		{name: 'bzsm' },
		{name: 'tjrm' },
		{name: 'tjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{name: 'fpdx' },
		{name: 'fpsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{name: 'htxh'  ,type: 'float'},
		{name: 'htbh'  ,type: 'float'},
		{name: 'ddxh'  ,type: 'float'},
		{name: 'ddbh'  ,type: 'float'},
		{name: 'ywms' },
		{ name: 'wxbh', type: 'float' }
	]
});
