Ext.define('erp.purchaseInspectionManage.model.ImpPurchaseInspetion', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'csbh' },
		{ name: 'htbh', type: 'float' },
		{ name: 'htxh', type: 'float' },
		{ name: 'hth' },
		{ name: 'jhh' },
		{ name: 'ddh' },
		{ name: 'clhh' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'jldw' },
		{ name: 'cgsl', type: 'float' },
		{ name: 'rksl', type: 'float' },
		{ name: 'cpmc' },
		{ name: 'khmc' },
		{ name: 'hsbm' },
		{ name: 'htbz' },
		{ name: 'pono' },
		{ name: 'cfbh', type: 'float' },
		{ name: 'cfxh', type: 'float' },
		{ name: 'cfh' },
		{ name: 'khbh' },
		{ name: 'csmc' },
		{ name: 'cpbh' },
		{ name: 'khxh' },
		{ name: 'ywms' },
		{ name: 'zxgz' },
		{ name: 'wxdh', type: 'float' },
		{ name: 'wxxh', type: 'float' },
		{ name: 'wxh' },
		{ name: 'xtcd', type: 'float' },
		{ name: 'xzbj', type: 'int' }
	]
});
