Ext.define('erp.view.master.perchasepriceadjust.model.Cgjgtzmxb', {
	extend: 'Ext.data.Model',
	fields: [
		{ name: 'tjdh', type: 'int' },
		{ name: 'tjxh', type: 'int' },
		{ name: 'csmc' },
		{ name: 'rkrq', type: 'date', dateFormat: 'Y-m-d H:i:s'  },
		{ name: 'clhh' },
		{ name: 'clmc' },
		{ name: 'cltx1' },
		{ name: 'jldw' },
		{ name: 'rksl', type: 'float'},
		{ name: 'rkdj', type: 'float'},
		{ name: 'rkje', type: 'float' },
		{ name: 'rkdb_yl_wbdj', type: 'float'},
		{ name: 'rkdb_yl_wbje', type: 'float'},
		{ name: 'thdj', type: 'float' },
		{ name: 'thje', type: 'float' },
		{ name: 'wbdh' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbdj', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'bzsm' },
		{ name: 'ckmc' },
		{ name: 'rkdh', type: 'float' },
		{ name: 'rkxh', type: 'float' },
		{ name: 'cpmc' },
		{ name: 'zcpmc' },
		{ name: 'ckbh' },
		{ name: 'qfbj', type: 'int' },
		{ name: 'qfrm' },
		{ name: 'qfsj',type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name: 'sdbj', type: 'int' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name: 'sdrm' },
		{ name: 'csdj', type: 'float' },
		{ name: 'csje', type: 'float' },
		{ name: 'tjbj', type: 'int' },
		{ name: 'tjrm' },
		{ name: 'tjsj', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name: 'tjdx'},
		{ name: 'csbh' },
		{ name: 'fzhm' },
		{ name: 'wbbh' },
		{ name: 'cpbh' },
		{ name: 'zcpbh' },
		{ name: 'hsbm' },
		{ name: 'wbmc'}
	]
});
