Ext.define('erp.view.master.perchasepriceadjust.model.RkdbImp', {
	extend: 'Ext.data.Model',
	fields: [
		{ name: 'ckbh' },
		{ name: 'rkdh', type: 'float' },
		{ name: 'rkxh', type: 'float' },
		{ name: 'rkrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'pjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'csbh' },
		{ name: 'clhh' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'jldw' },
		{ name: 'hwbh' },
		{ name: 'pcbh' },
		{ name: 'ghpc' },
		{ name: 'wbmc' },
		{ name: 'rksl', type: 'float' },
		{ name: 'rkdj', type: 'float' },
		{ name: 'rkje', type: 'float' },
		{ name: 'zzsl', type: 'float' },
		{ name: 'csdj', type: 'float' },
		{ name: 'csje', type: 'float' },
		{ name: 'cbdj', type: 'float' },
		{ name: 'cbje', type: 'float' },
		{ name: 'wbbh' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbdj', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'rklb', type: 'float' },
		{ name: 'jhbh', type: 'float' },
		{ name: 'jhxh', type: 'float' },
		{ name: 'htbh', type: 'float' },
		{ name: 'htxh', type: 'float' },
		{ name: 'dhdh', type: 'float' },
		{ name: 'dhxh', type: 'float' },
		{ name: 'wxbj', type: 'int' },
		{ name: 'wxdh', type: 'float' },
		{ name: 'wxxh', type: 'float' },
		{ name: 'wgbj', type: 'int' },
		{ name: 'sdbj', type: 'int' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'sdrm' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'dybj', type: 'int' },
		{ name: 'dysj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jkrm' },
		{ name: 'zzrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bzsm' },
		{ name: 'hcbj', type: 'int' },
		{ name: 'hcdh', type: 'float' },
		{ name: 'hcxh', type: 'float' },
		{ name: 'tzdh', type: 'float' },
		{ name: 'fzhm' },
		{ name: 'hxbj', type: 'int' },
		{ name: 'fplb' },
		{ name: 'fphm' },
		{ name: 'hxrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'hxrm' },
		{ name: 'hxsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'cfxh', type: 'float' },
		{ name: 'pddh', type: 'float' },
		{ name: 'shdh' },
		{ name: 'nbcbdj', type: 'float' },
		{ name: 'nbcbje', type: 'float' },
		{ name: 'fzdw' },
		{ name: 'fzsl', type: 'float' },
		{ name: 'shsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'sqbh', type: 'float' },
		{ name: 'sqxh', type: 'float' },
		{ name: 'tzxh', type: 'float' },
		{ name: 'xdzl', type: 'float' },
		{ name: 'zsbj', type: 'int' },
		{ name: 'gjbj', type: 'int' },
		{ name: 'fgjh', type: 'float' },
		{ name: 'fgxh', type: 'float' },
		{ name: 'fgcp' },
		{ name: 'cgbh', type: 'float' },
		{ name: 'cgxh', type: 'float' },
		{ name: 'glht', type: 'float' },
		{ name: 'bzbh', type: 'float' },
		{ name: 'rkdh_wms', type: 'float' },
		{ name: 'hth' },
		{ name: 'clmc' },
		{ name: 'csmc' },
		{ name: 'cpbh' },
		{ name: 'zcpbh' },
		{ name: 'cqbh_wms' },
		{ name: 'ckmc' },
		{ name: 'cpmc' },
		{ name: 'zcpmc' }
	]
});
