Ext.define('erp.materialTestEvaluation.model.MaterialTestEvaluation', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{header:'审核',  name: 'shbj', type: 'int',columnWidth:40,isSign:true },
		{header:'锁定',  name: 'sdbj', type: 'int',columnWidth:40,isSign:true },
		{header:'紧急度', name: 'jjdmc',columnWidth:80},
		{name: 'jjd', type: 'int' ,hidden:true},
		{header:'委托单号', name: 'wtdh', type: 'float' ,columnWidth:80},
		{header:'委托部门', name: 'wtlbmc' ,columnWidth:80},
		{ name: 'wtlb',hidden:true },
		{header:'委托人', name: 'wtrm' ,columnWidth:80},
		{ name: 'wtbm',hidden:true },
		{header:'样品委托日期', name: 'ypwtrq' ,type: 'date', dateFormat: 'Y-m-d H:i:s' ,columnWidth:90},
		{header:'供应厂商', name: 'csmc' ,columnWidth:160},
		{ name: 'csbh',hidden:true },
		{header:'评审', name: 'psbj' , type: 'int',columnWidth:40,isSign:true },
		{header:'检验', name: 'jybj' , type: 'int',columnWidth:40,isSign:true },
		{header:'材料货号', name: 'clhh' ,columnWidth:80},
		{name: 'plmth' ,columnWidth:80,hidden:true},
		{header:'事物特性', name: 'plmtx' ,columnWidth:80,hidden:true},
		{header:'材料名称', name: 'clmc' ,columnWidth:160},
		{header:'送检数量', name: 'sjsl' , type: 'float' ,columnWidth:80},
		{header:'单位', name: 'jldw' ,columnWidth:80},
		{header:'合同号', name: 'hth' ,columnWidth:80},
		{header:'订单号', name: 'ddh' ,columnWidth:80},
		{header:'客户简称', name: 'khjc' ,columnWidth:80},
		{ name: 'khbh',hidden:true },
		{header:'到货号', name: 'dhh' ,columnWidth:80},
		{header:'序号', name: 'wtxh' ,columnWidth:80,
		renderer : function(v) {
			return Ext.util.Format.number(v,
					'0');
		}},
		{header:'项目序号', name: 'wtsqxh' , type: 'float',columnWidth:80},
		{header:'测试项目', name: 'csxm' ,columnWidth:80},
		{header:'测试标准及方法', name: 'csbz' ,columnWidth:160},
		{header:'备注说明', name: 'wtjycssqmxb_bzsm' ,columnWidth:80},
		{header:'测试结论', name: 'jyjg' ,columnWidth:80},
		{header:'测试值', name: 'csz' ,columnWidth:80},
		{header:'测试价格', name: 'csjg' , type: 'float' ,columnWidth:80},
		{header:'测试周期', name: 'cszq' , type: 'int' ,columnWidth:80},
		{header:'测试总价', name: 'cszj', type: 'float' ,columnWidth:80},
		{header:'要求交期', name: 'yqjq' ,type: 'date', dateFormat: 'Y-m-d H:i:s' ,columnWidth:90},
		{header:'评审人', name: 'psrm' ,columnWidth:80},
		{header:'评审交期', name: 'psjq' ,type: 'date', dateFormat: 'Y-m-d H:i:s' ,columnWidth:90},
		{header:'评审时间', name: 'pssj' ,type: 'date', dateFormat: 'Y-m-d H:i:s' ,columnWidth:90},
		{header:'处理人', name: 'clrm' ,columnWidth:80},
		{header:'分配时间', name: 'fpsj' ,type: 'date', dateFormat: 'Y-m-d H:i:s' ,columnWidth:90},
		{header:'审核时间', name: 'shsj' ,type: 'date', dateFormat: 'Y-m-d H:i:s' ,columnWidth:90},
		{header:'检验人', name: 'jyrm_hz' ,columnWidth:80},
		{header:'检验时间', name: 'jysj_hz' ,type: 'date', dateFormat: 'Y-m-d H:i:s' ,columnWidth:90},
		{header:'委托日期', name: 'wtrq' ,type: 'date', dateFormat: 'Y-m-d H:i:s' ,columnWidth:90},
		{header:'来料日期', name: 'llrq' ,type: 'date', dateFormat: 'Y-m-d H:i:s' ,columnWidth:90},
		{header:'操作员', name: 'czym' ,columnWidth:80},
		{header:'操作时间', name: 'czsj' ,type: 'date', dateFormat: 'Y-m-d H:i:s' ,columnWidth:90},
		{header:'锁定人', name: 'sdrm' ,columnWidth:80},
		{header:'锁定时间', name: 'sdsj' ,type: 'date', dateFormat: 'Y-m-d H:i:s' ,columnWidth:90},
		
		{ name: 'sdrm' ,hidden:true },
		{ name: 'gdbj', type: 'int' ,hidden:true },
		{ name: 'gdbj_pd', type: 'int' ,hidden:true },
		{ name: 'bzsm' ,hidden:true },
		{ name: 'htbh', type: 'float' ,hidden:true },
		{ name: 'htxh', type: 'float' ,hidden:true },
		{ name: 'dhdh', type: 'float' ,hidden:true },
		{ name: 'dhxh', type: 'float' ,hidden:true },
		{ name: 'ckbh' ,hidden:true },
		{ name: 'bzsm' ,hidden:true },
		{ name: 'wjmc' ,hidden:true },
		{ name: 'wjlj' ,hidden:true },
		{ name: 'cjrm' ,hidden:true },
		{ name: 'cjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' ,hidden:true },
		{ name: 'jysj', type: 'date', dateFormat: 'Y-m-d H:i:s' ,hidden:true },
		{ name: 'jyrm' ,hidden:true }
	]
});
