Ext.define('erp.materialInspection.model.ArriveImp',{
    extend: 'Ext.data.Model',
	idProperty: 'dhh',
	fields: [
	 { name: 'ckbh' },
		{ name: 'dhdh', type: 'float' },
		{ name: 'dhxh', type: 'float' },
		{ name: 'dhrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'hth' },
		{ name: 'dhh' },
		{ name: 'csbh' },
		{ name: 'clhh' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'pcbh' },
		{ name: 'ghpc' },
		{ name: 'hth' },
		{ name: 'wxh' },
		{ name: 'jhh' },
		{ name: 'clth' },
		{ name: 'clmc' },
		{ name: 'ckmc' },
		{ name: 'csmc' },
		{ name: 'zzjl' },
		{ name: 'jlmc' },
		{ name: 'cpbh' },
		{ name: 'jhbz' },
		{ name: 'khbh' },
		{ name: 'khmc' },
		{ name: 'zcpbh' },
		{ name: 'zcpmc' },
		{ name: 'txgz' },
		{ name: 'dhsl', type: 'float' },
		{ name: 'yrsl', type: 'float' },
		{ name: 'wrsl', type: 'float' },
		{ name: 'jldw' },
		{ name: 'htbh', type: 'float' },
		{ name: 'htxh', type: 'float' },
		{ name: 'jhbh', type: 'float' },
		{ name: 'jhxh', type: 'float' },
		{ name: 'wtdh' },
		{ name: 'zzrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jhrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'wkjq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'sxrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'pjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jkrm' },
		{ name: 'bzsm' },
		{ name: 'zcpmc' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zjbj', type: 'int' },
		{ name: 'kjlx', type: 'int' },
		{ name: 'fzzbj', type: 'int' },
		{ name: 'jjbj', type: 'int' },
		{ name: 'ztbj', type: 'int' },
		{ name: 'jyjg', type: 'int' },
		{ name: 'gltk', type: 'int' },
		{ name: 'xzbj', type: 'int' },
		{ name: 'zjdh' },
		{ name: 'zjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zjbz' },
		{ name: 'dpyy' },
		{ name: 'dybj', type: 'int' },
		{ name: 'zjrm' },
		{ name: 'zjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'thdh', type: 'float' },
		{ name: 'thrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'thbj', type: 'int' },
		{ name: 'wxbj', type: 'int' },
		{ name: 'wxdh', type: 'float' },
		{ name: 'wxxh', type: 'float' },
		{ name: 'shdh' },
		{ name: 'fzsl', type: 'float' },
		{ name: 'fzdw' },
		{ name: 'hwbh' },
		{ name: 'shrm' },
		{ name: 'wxh' },
		{ name: 'jhh' },
		{ name: 'ddh' },
		{ name: 'shsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'shjg' },
		{ name: 'shsm' },
		{ name: 'zzbj', type: 'int' },
		{ name: 'zzrm' },
		{ name: 'zzsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'shbj', type: 'int' }
	]
})