Ext.define('erp.materialQualityTesting.model.QueryParams', {
	extend: 'Ext.data.Model',
	fields: [		
		{ name: 'checkbox_dhdh' },
		{ name: 'dhdh1' },
		{ name: 'dhdh2' },
		{ name: 'checkbox_dhrq' },
		{ name: 'dhrq1' },
		{ name: 'dhrq2' },
		{ name: 'checkbox_zjdh' },
		{ name: 'zjdh1' },
		{ name: 'zjdh2' },
		{ name: 'checkbox_zjrq' },
		{ name: 'zjrq1' },
		{ name: 'zjrq2' },
		{ name: 'checkbox_csbh' },
		{ name: 'csbh' },
		{ name: 'checkbox_clmc' },
		{ name: 'clmc' },
		{ name: 'checkbox_ckbh' },
		{ name: 'ckbh' },
		{ name: 'checkbox_jyjg' },
		{ name: 'jyjg' },
		{ name: 'checkbox_pcbh' },
		{ name: 'pcbh' },
		{ name: 'checkbox_hth' },	
		{ name: 'hth1' },
		{ name: 'hth2' },
		{ name: 'checkbox_cllb'},
		{ name: 'lbbh' },	
		{ name: 'checkbox_ztbj'},
		{ name: 'ztbj' }
	]
});