Ext.define('erp.payApply.model.ContractDetail', {
    extend:'Ext.data.Model',
    idProperty:'htbh'+'htxh',
    fields: [
        { name: 'htbh', type: 'int' },
		{ name: 'htxh', type: 'int' },
		{ name: 'jhh' },
		{ name: 'hth' },
		{ name: 'clhh' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'jldw' },
		{ name: 'cgsl', type: 'float' },
		{ name: 'dhrk', type: 'float' },
		{ name: 'wrsl', type: 'float' },
		{ name: 'cgbh', type: 'int' },
		{ name: 'cgxh', type: 'int' },
		{ name: 'jhbh', type: 'int' },
		{ name: 'jhxh', type: 'int' },
		{ name: 'sxrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jhbz' },
		{ name: 'csbh' },
		{ name: 'clth' },
		{ name: 'clmc' },
		{ name: 'zjbj', type: 'int' },
		{ name: 'fzzbj', type: 'int' },
		{ name: 'txgz' },
		{ name: 'hsbm' },
		{ name: 'fzdw' },
		{ name: 'fzsl', type: 'float' },
		{ name: 'kjlx', type: 'int' },
		{ name: 'cgdj', type: 'float' },
		{ name: 'cgje', type: 'float' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbbh' },
		{ name: 'wbdj', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'plmth' },
		{ name: 'plmtx' },
		{ name: 'csmc'},
		{ name: 'wbdh'}
    ]
	
})