Ext.define('erp.payApply.model.FeeReimbursementImp', {
	extend: 'Ext.data.Model',
	idProperty: 'jlh',
	fields: [
		{ name: 'bxrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'ccrm' },
		{ name: 'ccsy' },
		{ name: 'tjbj', type: 'int' },
		{ name: 'tjrm' },
		{ name: 'lkrm' },
		{ name: 'gdbj', type: 'int' },
		{ name: 'bxrm' },
		{ name: 'qrbj', type: 'int' },
		{ name: 'dybj', type: 'int' },
		{ name: 'dyrm' },
		{ name: 'qrrm' },
		{ name: 'qrrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bzsm' },
		{ name: 'yfbj', type: 'int' },
		{ name: 'yfsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bxbm' },
		{ name: 'tjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tjdx' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'spsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'spbj', type: 'int' },
		{ name: 'sprm' },
		{ name: 'wbbh' },
		{ name: 'wbdh' },
		{ name: 'jlbh', type: 'float' },
		{ name: 'jlxh', type: 'float' },
		{ name: 'jlh' },
		{ name: 'qsrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jzrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'pjhm' },
		{ name: 'pjje', type: 'float' },
		{ name: 'qtje', type: 'float' },
		{ name: 'hjje', type: 'float' },
		{ name: 'wqje', type: 'float' },
		{ name: 'zflb' },
		{ name: 'sjfylb' },
		{ name: 'fsbm' },
		{ name: 'hsbm' },
		{ name: 'zgxm' },
		{ name: 'bmmc1' },
		{ name: 'bmmc2' },
		{ name: 'bmmc3' },
		{ name: 'lbmc1' },
		{ name: 'lbmc2' },
		{ name: 'bxsy' }
	]
});
