Ext.define('erp.payApply.model.Fpwd', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'ckbh' },
		{ name: 'rkdh', type: 'float' },
		{ name: 'rkxh', type: 'float' },
		{ name: 'rkrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'csbh' },
		{ name: 'clhh' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'jldw' },
		{ name: 'cgsl', type: 'float' },
		{ name: 'dhsl', type: 'float' },
		{ name: 'rksl', type: 'float' },
		{ name: 'rkdj', type: 'float' },
		{ name: 'rkje', type: 'float' },
		{ name: 'wbbh' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbdj', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'rklb' },
		{ name: 'hth' },
		{ name: 'hcdh', type: 'float' },
		{ name: 'hcxh', type: 'float' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bzsm' },
		{ name: 'clmc' },
		{ name: 'yhbh' },
		{ name: 'cglb' },
		{ name: 'csmc' },
		{ name: 'dhrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'sjly' },
		{ name: 'fzdw' },
		{ name: 'fzsl', type: 'float' },
		{ name: 'shdh' },
		{ name: 'shsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tzdh', type: 'float' }
	]
});
