Ext.define('erp.payApply.model.Htmx', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'htbh', type: 'float' },
		{ name: 'htxh', type: 'float' },
		{ name: 'jhh' },
		{ name: 'hth' },
		{ name: 'clhh' },
		{ name: 'cltx1' },
		{ name: 'cltx2' },
		{ name: 'cltx3' },
		{ name: 'jldw' },
		{ name: 'cjsl', type: 'float' },
		{ name: 'cgsl', type: 'float' },
		{ name: 'dhrk', type: 'float' },
		{ name: 'wrsl', type: 'float' },
		{ name: 'jhyl', type: 'float' },
		{ name: 'jhdh', type: 'float' },
		{ name: 'jhwd', type: 'float' },
		{ name: 'cgbh', type: 'float' },
		{ name: 'cgxh', type: 'float' },
		{ name: 'jhbh', type: 'float' },
		{ name: 'jhxh', type: 'float' },
		{ name: 'sxrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jhbz' },
		{ name: 'csbh' },
		{ name: 'clth' },
		{ name: 'clmc' },
		{ name: 'zjbj', type: 'int' },
		{ name: 'fzzbj', type: 'int' },
		{ name: 'txgz' },
		{ name: 'hsbm' },
		{ name: 'fzdw' },
		{ name: 'fzsl', type: 'float' },
		{ name: 'kjlx', type: 'int' },
		{ name: 'cgdj', type: 'float' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbbh' },
		{ name: 'wbdj', type: 'float' },
		{ name: 'cgje', type: 'float' },
		{ name: 'wbje', type: 'float' }
	]
});
