Ext.define('erp.payApply.model.PayApply', {
	extend: 'Ext.data.Model',
	idProperty: 'sqbh',
	fields: [
		{ name: 'sqbh', type: 'float' },
		{ name: 'sqrq', type: 'date', dateFormat: 'Y-m-d H:i:s'},
		{ name: 'sqbm'},
		{ name: 'sqrm'},
		{ name: 'sqje', type: 'float' },
		{ name: 'yotu'},
		{ name: 'fkfs'},
		{ name: 'fkqx', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'bzsm'},
		{ name: 'spbj', type: 'int' },
		{ name: 'sprm'},
		{ name: 'spyj'},
		{ name: 'spsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'yfbj', type: 'int' },
		{ name: 'qrrm'},
		{ name: 'qrsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gdbj', type: 'int' },
		{ name: 'yhbh'},
		{ name: 'csbh'},
		{ name: 'cszh'},
		{ name: 'khyh'},
		{ name: 'fphm'},
		{ name: 'htbh', type: 'float' },
		{ name: 'tjrm'},
		{ name: 'tjbj', type: 'int'  },
		{ name: 'tjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tjdx'},
		{ name: 'yfje', type: 'float' },
		{ name: 'wbyf', type: 'float' },
		{ name: 'yfkbj',type: 'int'  },
		{ name: 'ztdw'},
		{ name: 'ztmc'},
		{ name: 'hsbm'},
		{ name: 'fhbj',type: 'int'  },
		{ name: 'fhrm'},
		{ name: 'fhsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'wbbh'},
		{ name: 'wbdh'},
		{ name: 'wbhl' , type: 'float' },
		{ name: 'wbje' , type: 'float' },
		{ name: 'hdbj',  type: 'int'},
		{ name: 'csmc'},
		{ name: 'skdw'},
		{ name: 'cgym'},
		{ name: 'cgyxm'},
		{ name: 'skdwmc'},
		{ name: 'yfkje' , type: 'float' },
		{ name: 'yfkwb' , type: 'float' },
		{ name: 'wcbj',type: 'int'  },
		{ name: 'dybj',type: 'int'  },
		{ name: 'dyrm'},
		{ name: 'dysj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'yzbj',type: 'int'  },
		{ name: 'yzrm'},
		{ name: 'yzsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zzbj',type: 'int'  },
		{ name: 'fhyj'},
		{ name: 'sjly'},
		{ name: 'fktj'},
		{ name: 'fkts', type: 'float' },
		{ name: 'kpdj'},
		{ name: 'zfrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zyze', type: 'float' },
		{ name: 'ywlx'},
		{ name: 'sqbmbh'}
	]
});
