Ext.define('erp.payApply.model.PurchaseFeeImp', {
	extend: 'Ext.data.Model',
	idProperty: 'fyh',
	fields: [
		{ name: 'fydh', type: 'float' },
		{ name: 'fyxh', type: 'float' },
		{ name: 'fyh' },
		{ name: 'fyrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'yhbh' },
		{ name: 'cglb' },
		{ name: 'csbh' },
		{ name: 'fyzy' },
		{ name: 'fktj' },
		{ name: 'ztdw' },
		{ name: 'ztmc' },
		{ name: 'cszh' },
		{ name: 'khyh' },
		{ name: 'fkts' , type: 'float' },
		{ name: 'fysl', type: 'float' },
		{ name: 'fydj', type: 'float' },
		{ name: 'fyje', type: 'float' },
		{ name: 'sqje', type: 'float' },
		{ name: 'wqje', type: 'float' },
		{ name: 'zzsl', type: 'float' },
		{ name: 'csdj', type: 'float' },
		{ name: 'csje', type: 'float' },
		{ name: 'zzse', type: 'float' },
		{ name: 'jhbh', type: 'float' },
		{ name: 'jhxh', type: 'float' },
		{ name: 'jhh' },
		{ name: 'htbh', type: 'float' },
		{ name: 'htxh', type: 'float' },
		{ name: 'hth' },
		{ name: 'bzsm' },
		{ name: 'hxbj', type: 'int' },
		{ name: 'fplb' },
		{ name: 'fphm' },
		{ name: 'sdbj', type: 'int' },
		{ name: 'sdrm' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tzdh', type: 'float' },
		{ name: 'csmc' },
		{ name: 'hsdh', type: 'float' },
		{ name: 'hsxh', type: 'float' },
		{ name: 'hsbm' },
		{ name: 'bmmc' },
		{ name: 'spbj', type: 'int' },
		{ name: 'sprm' },
		{ name: 'spyj' },
		{ name: 'spsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tjbj', type: 'int' },
		{ name: 'tjrm' },
		{ name: 'tjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tjdx' },
		{ name: 'fylx' },
		{ name: 'cybh' },
		{ name: 'hsh' },
		{ name: 'fpdx' },
		{ name: 'fyxz' },
		{ name: 'wbbh' },
		{ name: 'wbdh' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'wbsq', type: 'float' },
		{ name: 'wqwb', type: 'float' },
		{ name: 'wxdh', type: 'float' },
		{ name: 'wxxh', type: 'float' },
		{ name: 'wxh' }
	]
});
