Ext.define('erp.payApply.model.QueryParams', {
	extend: 'Ext.data.Model',
	fields: [		
		{ name: 'checkbox_sqbh'},
		{ name: 'sqbh1' },
		{ name: 'sqbh2' },
		{ name: 'checkbox_sqrq' },
		{ name: 'sqrq1' },
		{ name: 'sqrq2' },
		{ name: 'checkbox_yfkbj'},
		{ name: 'yfkbj' },
		{ name: 'checkbox_csmc'},
		{ name: 'csmc' },
		{ name: 'checkbox_skdw'},
		{ name: 'skdw' },
		{ name: 'checkbox_khyh'},
		{ name: 'khyh' },
		{ name: 'checkbox_fkfs'},
		{ name: 'fkfs' },
		{ name: 'checkbox_htbh'},
		{ name: 'htbh1' },
		{ name: 'htbh2' },
		{ name: 'checkbox_hsbm'},
		{ name: 'hsbm' },
		{ name: 'checkbox_sqbm'},
		{ name: 'sqbm' },
		{ name: 'checkbox_sqrm'},
		{ name: 'sqrm' }
	]
});
