Ext.define('erp.payApply.model.SaleFeeImp', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'fydh', type: 'float' },
		{ name: 'fyxh', type: 'float' },
		{ name: 'fyh' },
		{ name: 'khbh' },
		{ name: 'fysl' , type: 'float' },
		{ name: 'fydj' , type: 'float' },
		{ name: 'zzsl' , type: 'float' },
		{ name: 'csdj' , type: 'float' },
		{ name: 'csje' , type: 'float' },
		{ name: 'zzse' , type: 'float' },
		{ name: 'fkts' , type: 'float' },
		{ name: 'fyje', type: 'float' },
		{ name: 'sqje', type: 'float' },
		{ name: 'wqje', type: 'float' },
		{ name: 'wbbh' },
		{ name: 'wbdh' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'wbsq', type: 'float' },
		{ name: 'wqwb', type: 'float' },
		{ name: 'fyrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'fktj' },
		{ name: 'fkts' , type: 'float' },
		{ name: 'sdbj' , type: 'int' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'sdrm' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czym' },
		{ name: 'csbh' },
		{ name: 'csmc' },
		{ name: 'cszh' },
		{ name: 'khyh' },
		{ name: 'ztdw' },
		{ name: 'ztmc' },
		{ name: 'yhbh' },
		{ name: 'hsbm' },
		{ name: 'bmmc' },
		{ name: 'xslb' },
		{ name: 'czym' },
		{ name: 'lbmc' },
		{ name: 'lbmc1' },
		{ name: 'ddbh', type: 'float' },
		{ name: 'ddxh', type: 'float' },
		{ name: 'ddh' },
		{ name: 'khmc' },
		{ name: 'csbh' },
		{ name: 'fyzy' },
		{ name: 'fylb' },
		{ name: 'bzsm' }
	]
});
