Ext.define('erp.payApply.model.SupplyInvoiceImp', {
	extend: 'Ext.data.Model',
	idProperty: 'fplb'+'fphm',
	fields: [
		{ name: 'fplb' },
		{ name: 'fphm' },
		{ name: 'csbh' },
		{ name: 'fpje', type: 'float' },
		{ name: 'rkje', type: 'float' },
		{ name: 'csje', type: 'float' },
		{ name: 'yfkje', type: 'float' },
		{ name: 'sqje', type: 'float' },
		{ name: 'wqje', type: 'float' },
		{ name: 'bzsm' },
		{ name: 'jzrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'kprq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'yhbh' },
		{ name: 'fktj' },
		{ name: 'fkts' , type: 'float' },
		{ name: 'csmc' },
		{ name: 'cszh' },
		{ name: 'khyh' },
		{ name: 'skdw' },
		{ name: 'mrdw' },
		{ name: 'ztdw' },
		{ name: 'ztmc' },
		{ name: 'hsbm' },
		{ name: 'bmmc' },
		{ name: 'wbbh' },
		{ name: 'wbdh' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'yfwb', type: 'float' },
		{ name: 'wbsq', type: 'float' },
		{ name: 'wqwb', type: 'float' },
		{ name: 'fptt' },
		{ name: 'fpttbh' },
		{ name: 'cgym' },
		{ name: 'ycbj', type: 'int' },
		{ name: 'xzbj', type: 'int' }
	]
});
