Ext.define('erp.payApply.model.Wdfy', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'fydh', type: 'float' },
		{ name: 'fyxh', type: 'float' },
		{ name: 'fyrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'yhbh' },
		{ name: 'cglb' },
		{ name: 'csbh' },
		{ name: 'fyzy' },
		{ name: 'fysl', type: 'float' },
		{ name: 'fydj', type: 'float' },
		{ name: 'fyje', type: 'float' },
		{ name: 'zzsl', type: 'float' },
		{ name: 'csdj', type: 'float' },
		{ name: 'csje', type: 'float' },
		{ name: 'zzse', type: 'float' },
		{ name: 'jhbh', type: 'float' },
		{ name: 'jhxh', type: 'float' },
		{ name: 'jhh' },
		{ name: 'htbh', type: 'float' },
		{ name: 'htxh', type: 'float' },
		{ name: 'hth' },
		{ name: 'bzsm' },
		{ name: 'hxbj', type: 'int' },
		{ name: 'fplb' },
		{ name: 'fphm' },
		{ name: 'sdbj', type: 'int' },
		{ name: 'sdrm' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tzdh', type: 'float' },
		{ name: 'csmc' }
	]
});
