Ext.define('erp.master.purchaseCost.model.AbnormalImp', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'ycdh', type: 'float' },
		{ name: 'khbh' },
		{ name: 'scdh' },
		{ name: 'yclx' },
		{ name: 'jlxh' },
		{ name: 'yczt' },
		{ name: 'cybh' },
		{ name: 'cpbh' },
		{ name: 'cpmc' },
		{ name: 'khmc' },
		{ name: 'ddh' },
		{ name: 'jhh' },
		{ name: 'dyh' },
		{ name: 'cyh' },
		{ name: 'csbh' },
		{ name: 'sqrm' },
		{ name: 'zrrm' },
		{ name: 'bzsm' },
		{ name: 'plmth' },
		{ name: 'plmtx' },
		{ name: 'sdbj', type: 'int' },
		{ name: 'sdrm' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czrm' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'wcbj', type: 'int' },
		{ name: 'wcrm' },
		{ name: 'wcsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gdbj', type: 'int' },
		{ name: 'jhlb' },
		{ name: 'jhlbmc' },
		{ name: 'fsrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czy_gh' },
		{ name: 'ddbh', type: 'float' },
		{ name: 'ddxh', type: 'float' },
		{ name: 'jhbh', type: 'float' },
		{ name: 'jhxh', type: 'float' },
		{ name: 'dydh', type: 'float' },
		{ name: 'dyxh', type: 'float' },
		{ name: 'cyxh', type: 'float' },
		{ name: 'ycje', type: 'float' },
		{ name: 'djly' },
		{ name: 'ycms' },
		{ name: 'csmc' },
		{ name: 'tjbj', type: 'int' },
		{ name: 'tjrm' },
		{ name: 'tjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'tjdx' },
		{ name: 'spbj', type: 'int' },
		{ name: 'sprm' },
		{ name: 'spsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'complaint_id', type: 'float' },
		{ name: 'order_number', type: 'float' }
	]
});
