Ext.define('erp.master.purchaseCost.model.CallinImp', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'dbdh', type: 'float' },
		{ name: 'dbxh', type: 'float' },
		{ name: 'dckh' },
		{ name: 'dcckmc' },
		{ name: 'drckmc' },
		{ name: 'dbh' },
		{ name: 'ddh' },
		{ name: 'tzh' },
		{ name: 'dcrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'drrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'drkh' },
		{ name: 'cpbh' },
		{ name: 'cptx1' },
		{ name: 'cptx2' },
		{ name: 'cptx3' },
		{ name: 'jldw' },
		{ name: 'drhw' },
		{ name: 'dchw' },
		{ name: 'zcpc' },
		{ name: 'zrpc' },
		{ name: 'dblb', type: 'float' },
		{ name: 'dbsl', type: 'float' },
		{ name: 'dbdj', type: 'float' },
		{ name: 'nbdbdj', type: 'float' },
		{ name: 'dbxs', type: 'float' },
		{ name: 'ddbh', type: 'float' },
		{ name: 'ddxh', type: 'float' },
		{ name: 'tzbh', type: 'float' },
		{ name: 'tzxh', type: 'float' },
		{ name: 'bzsm' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'qrbj', type: 'int' },
		{ name: 'qrrm' },
		{ name: 'qrsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'dybj', type: 'int' },
		{ name: 'dysj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'dbfs' },
		{ name: 'ysxs', type: 'float' },
		{ name: 'mxtj', type: 'float' },
		{ name: 'wdtj', type: 'float' },
		{ name: 'wdje', type: 'float' },
		{ name: 'ystj', type: 'float' },
		{ name: 'ysdj', type: 'float' },
		{ name: 'ysje', type: 'float' },
		{ name: 'zyrm' },
		{ name: 'htbz' },
		{ name: 'cpmc' },
		{ name: 'plmth' },
		{ name: 'plmtx' },
		{ name: 'sgtzh' },
		{ name: 'xzbj',type: 'int' },
		{ name: 'dbdh_wms', type: 'float' },
		{ name: 'bddh_wms', type: 'float' },
		{ name: 'cqbh_wms' }
	]
});
