Ext.define('erp.master.purchaseCost.model.LoadingCostsImp', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'zgbh', type: 'float' },
		{ name: 'zgxh', type: 'float' },
		{ name: 'fyxh', type: 'float' },
		{ name: 'tgrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zysj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'zgfs' },
		{ name: 'jzxx' },
		{ name: 'fzbj', type: 'int' },
		{ name: 'jcbj', type: 'int' },
		{ name: 'ycbj', type: 'int' },
		{ name: 'csbh' },
		{ name: 'csmc' },
		{ name: 'zgh' },
		{ name: 'zgtj', type: 'float' },
		{ name: 'zgdj', type: 'float' },
		{ name: 'zgje', type: 'float' },
		{ name: 'jcje', type: 'float' },
		{ name: 'zgfy', type: 'float' },
		{ name: 'ydtj', type: 'float' },
		{ name: 'wdtj', type: 'float' },
		{ name: 'ydfy', type: 'float' },
		{ name: 'wdfy', type: 'float' },
		{ name: 'jzrm' },
		{ name: 'czrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'czrm' },
		{ name: 'ccgm' },
		{ name: 'ckmc' },
		{ name: 'bzsm' }
	]
});
