Ext.define('erp.master.purchaseCost.model.ProductEntrustImp', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'wtdh', type: 'float' },
		{ name: 'wtxh', type: 'float' },
		{ name: 'wtdj', type: 'float' },
		{ name: 'wtje', type: 'float' },
		{ name: 'ddbh', type: 'float' },
		{ name: 'ddxh', type: 'float' },
		{ name: 'sjsl', type: 'float' },
		{ name: 'sjdh', type: 'float' },
		{ name: 'sjxh', type: 'float' },
		{ name: 'wtbm' },
		{ name: 'wtlb' },
		{ name: 'wtrm' },
		{ name: 'wth' },
		{ name: 'ddh' },
		{ name: 'jldw' },
		{ name: 'sjh' },
		{ name: 'cpbh' },
		{ name: 'cpmc' },
		{ name: 'ckbh' },
		{ name: 'ckmc' },
		{ name: 'plmth' },
		{ name: 'plmtx' },
		{ name: 'wtrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'llrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'khbh' },
		{ name: 'sdbj', type: 'int' },
		{ name: 'sdrm' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jybj', type: 'int' },
		{ name: 'gdbj', type: 'int' },
		{ name: 'gdbj_pd', type: 'int' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'shbj', type: 'int' },
		{ name: 'xzbj', type: 'int' },
		{ name: 'bzsm' },
		{ name: 'jysj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'csmd' },
		{ name: 'csjg' },
		{ name: 'cslx' },
		{ name: 'khmc' },
		{ name: 'qfbj', type: 'int' }
	]
});
