Ext.define('erp.master.purchaseCost.model.SendoutImp', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'ckbh' },
		{ name: 'ckmc' },
		{ name: 'fhdh', type: 'float' },
		{ name: 'fhxh', type: 'float' },
		{ name: 'fhrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'pjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'khbh' },
		{ name: 'ywym' },
		{ name: 'cpbh' },
		{ name: 'cptx1' },
		{ name: 'cptx2' },
		{ name: 'cptx3' },
		{ name: 'jldw' },
		{ name: 'hwbh' },
		{ name: 'pcbh' },
		{ name: 'fhxs', type: 'float' },
		{ name: 'fhlb', type: 'float' },
		{ name: 'fhsl', type: 'float' },
		{ name: 'bzdj', type: 'float' },
		{ name: 'xszk', type: 'float' },
		{ name: 'xsdj', type: 'float' },
		{ name: 'xsje', type: 'float' },
		{ name: 'zzsl', type: 'float' },
		{ name: 'csdj', type: 'float' },
		{ name: 'csje', type: 'float' },
		{ name: 'cbdj', type: 'float' },
		{ name: 'cbje', type: 'float' },
		{ name: 'nbcbdj', type: 'float' },
		{ name: 'nbcbje', type: 'float' },
		{ name: 'wbbh' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'wbdj', type: 'float' },
		{ name: 'wbje', type: 'float' },
		{ name: 'ddbh', type: 'float' },
		{ name: 'ddxh', type: 'float' },
		{ name: 'cybh' },
		{ name: 'cyxh', type: 'float' },
		{ name: 'tzbh', type: 'float' },
		{ name: 'tzxh', type: 'float' },
		{ name: 'sjdh', type: 'float' },
		{ name: 'sjxh', type: 'float' },
		{ name: 'bzsm' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'hdbj', type: 'int' },
		{ name: 'sdbj', type: 'int' },
		{ name: 'sdrm' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'dybj', type: 'int' },
		{ name: 'dysj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'jybj', type: 'int' },
		{ name: 'xsbj', type: 'int' },
		{ name: 'jzbj', type: 'float' },
		{ name: 'zrbj', type: 'int' },
		{ name: 'fzhm' },
		{ name: 'hxbj', type: 'int' },
		{ name: 'fplb' },
		{ name: 'fphm' },
		{ name: 'hxrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'hxrm' },
		{ name: 'hxsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'cfxh', type: 'float' },
		{ name: 'cwqrbj', type: 'int' },
		{ name: 'cwqrrm' },
		{ name: 'cwqrsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'dydh', type: 'float' },
		{ name: 'dyxh', type: 'float' },
		{ name: 'fhtzdh', type: 'float' },
		{ name: 'fhtzxh', type: 'float' },
		{ name: 'zgrm' },
		{ name: 'mxtj', type: 'float' },
		{ name: 'hjtj', type: 'float' },
		{ name: 'wdtj', type: 'float' },
		{ name: 'xslb' },
		{ name: 'gzdh' },
		{ name: 'cpmc' },
		{ name: 'plmth' },
		{ name: 'plmtx' },
		{ name: 'cpmc' },
		{ name: 'gzxh', type: 'float' },
		{ name: 'wms_ck' },
		{ name: 'drpycbj', type: 'int' },
		{ name: 'xzbj', type: 'int' },
		{ name: 'cqbh_wms' },
		{ name: 'fhdh_wms', type: 'float' },
		{ name: 'zdkh' },
		{ name: 'zddj', type: 'float' },
		{ name: 'zdje', type: 'float' },
		{ name: 'sjzgbh', type: 'float' },
		{ name: 'sjzgxh', type: 'float' }
	]
});
