Ext.define('erp.master.purchaseCost.model.SendImp', {
	extend: 'Ext.data.Model',
	idProperty: '',
	fields: [
		{ name: 'jlbh', type: 'float' },
		{ name: 'xslb' },
		{ name: 'ywym' },
		{ name: 'dsdw' },
		{ name: 'dsfs', type: 'float' },
		{ name: 'dsyq' },
		{ name: 'ypzl', type: 'float' },
		{ name: 'dsfy', type: 'float' },
		{ name: 'fkfs', type: 'float' },
		{ name: 'jsbj', type: 'int' },
		{ name: 'jbrm' },
		{ name: 'wtrm' },
		{ name: 'sjdw' },
		{ name: 'sjdh' },
		{ name: 'sjrm' },
		{ name: 'czym' },
		{ name: 'czsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'gdbj', type: 'int' },
		{ name: 'hsbm' },
		{ name: 'sjdz' },
		{ name: 'jjrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'sqrq', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'qfbj', type: 'int' },
		{ name: 'cybh' },
		{ name: 'fffs', type: 'float' },
		{ name: 'sfbj', type: 'int' },
		{ name: 'sdrm' },
		{ name: 'sdsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'sdbj', type: 'int' },
		{ name: 'yjrm' },
		{ name: 'yjsj', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'yjbj', type: 'int' },
		{ name: 'tj', type: 'float' },
		{ name: 'jfzl', type: 'float' },
		{ name: 'khbh' },
		{ name: 'dfzh' },
		{ name: 'dsxs', type: 'float' },
		{ name: 'wdje', type: 'float' },
		{ name: 'bzsm' },
		{ name: 'kdlx' },
		{ name: 'djlx' },
		{ name: 'csmc' },
		{ name: 'fphm' },
		{ name: 'wbfy', type: 'float' },
		{ name: 'wbbh' },
		{ name: 'wbhl', type: 'float' },
		{ name: 'kdry' },
		{ name: 'csbh' },
		{ name: 'ssbm' },
		{ name: 'ydfy', type: 'float' },
		{ name: 'gbdq' },
		{ name: 'cybh_hz' },
		{ name: 'yjyf', type: 'float' }
	]
});
