Ext.define('erp.view.main.region.AccountInfoWin',{
	extend:'erp.ux.Window',
	alias:'widget.mng_AccountInfoWin',
	requires:['erp.user.model.UserInfo'],
	title:'账号信息维护',
	glyph:0xf05a,
	width:500,
//	height:300,
	initComponent:function(){
		var me=this;
		Ext.apply(me,{
			items:[{
			  padding:5,
			  xtype:'form',
			  layout:'column',
			  defaults:{xtype:'textfield',columnWidth:.5,labelWidth:60,padding:2},
			  items:[{
			 	fieldLabel:'登陆ID',
			 	disabled:true,
			 	name:'login_id'
			  },{
			  	fieldLabel:'用户姓名',
			  	name:'user_name',
			  	allowBlank:false,
			  	blankText:'请输入姓名!'
			  },{
			  	fieldLabel:'性别',
			  	name:'gender',
			  	xtype:'combo',
			  	queryMode:'local',
			  	displayField:'name',
			  	valueField:'value',
			  	store:erp.DataUtil.getComboStore(erp.Const.SEX_TYPE)
			  },{
			  	fieldLabel:'出生日期',
			  	xtype:'datefield',
			  	dateFormat:'Y-m-d',
			  	name:'birthday',
			  	editable:false
			  },
			  { fieldLabel:'办公室',
			  	name:'office'
			  },{
			  	fieldLabel:'联系电话',
			  	name:'tel_no'
			  },{
			  	fieldLabel:'手机号码',
			  	name:'mobile'
			  },{
			  	fieldLabel:'电子邮箱',
			  	name:'email'
			  },{
			  	fieldLabel:'QQ',
			  	name:'qq_no'
			  },{
			  	fieldLabel:'是否有效',
			  	xtype:'checkbox',
			  	disabled:true,
			  	name:'isvalid'
			  },{
			  	fieldLabel:'最近一次登陆',
			  	labelWidth:90,
			  	xtype:'datefield',
			  	disabled:true,
			  	name:'last_login'
			  },
			  {
			  	fieldLabel:'登陆次数',
			  	disabled:true,
			  	name:'login_times'
			  }
			  ]
			}],
			buttons:[{text:'保存',glyph:0xf0c7,handler:'onSaveUserInfo'},{text:'关闭',glyph:0xf00d,handler:function(){me.close()}}]
		});
		this.callParent();
		var userRec=Ext.create('erp.user.model.UserInfo',erp.Util.currentUser.userInfo);
		this.down('form').loadRecord(userRec);
	}
})
